using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private SharedTransformSystem _xformSystem;

    private EntityUid? _shuttleEntity;

    public NavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();

        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = NavRadar.ShowIFF;

        IFFShuttleToggle.OnToggled += OnIFFShuttleTogglePressed;
        IFFShuttleToggle.Pressed = NavRadar.ShowIFFShuttles;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;

        // Frontier - IFF search
        IffSearchCriteria.OnTextChanged += args => OnIffSearchChanged(args.Text);
    }

    // Frontier - IFF search
    private void OnIffSearchChanged(string text)
    {
        text = text.Trim();

        NavRadar.IFFFilter = text.Length == 0
            ? null // If empty, do not filter
            : (entity, grid, iff) => // Otherwise use simple search criteria
            {
                _entManager.TryGetComponent<MetaDataComponent>(entity, out var metadata);
                return metadata != null && metadata.EntityName.Contains(text, StringComparison.OrdinalIgnoreCase);
            };
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;

        // Frontier - PR #1284 Add Shuttle Designation
        if (_entManager.TryGetComponent<MetaDataComponent>(shuttle, out var metadata))
        {
            var shipNameParts = metadata.EntityName.Split(' ');
            var designation = shipNameParts[^1];
            if (designation[2] == '-')
            {
                NavDisplayLabel.Text = string.Join(' ', shipNameParts[..^1]);
                ShuttleDesignation.Text = designation;
            }
            else
                NavDisplayLabel.Text = metadata.EntityName;
        }
        // End Frontier - PR #1284
    }

    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFF ^= true;
        args.Button.Pressed = NavRadar.ShowIFF;
    }

    private void OnIFFShuttleTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFFShuttles ^= true;
        args.Button.Pressed = NavRadar.ShowIFFShuttles;
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) ||
            !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        {
            return;
        }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = worldMatrix.Transform(gridBody.LocalCenter);

        // Get the positive reduced angle.
        var displayRot = -worldRot.Reduced();

        GridPosition.Text = $"{worldPos.X:0.0}, {worldPos.Y:0.0}";
        GridOrientation.Text = $"{displayRot.Degrees:0.0}";

        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = displayRot.RotateVec(gridVelocity);
        // Get linear velocity relative to the console entity
        GridLinearVelocity.Text = $"{gridVelocity.X + 10f * float.Epsilon:0.0}, {gridVelocity.Y + 10f * float.Epsilon:0.0}";
        GridAngularVelocity.Text = $"{-gridBody.AngularVelocity + 10f * float.Epsilon:0.0}";
    }
}
