using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.Dataset;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Random.Helpers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface; // Frontier
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Content.Shared._NF.Bank; // Frontier

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutWindow : FancyWindow
{
    public event Action<string>? OnNameChanged;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    private List<LoadoutGroupContainer> _groups = new();

    // Frontier
    private string _searchText = string.Empty;
    private Control? _tabButtonContainer;
    // End Frontier

    public HumanoidCharacterProfile Profile;

    // CCvar.
    private int _maxLoadoutNameLength;

    public LoadoutWindow(HumanoidCharacterProfile profile, RoleLoadout loadout, RoleLoadoutPrototype proto, ICommonSession session, IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        Profile = profile;
        var protoManager = collection.Resolve<IPrototypeManager>();
        var configManager = collection.Resolve<IConfigurationManager>();

        _maxLoadoutNameLength = configManager.GetCVar(CCVars.MaxLoadoutNameLength);
        RoleNameEdit.IsValid = text => text.Length <= _maxLoadoutNameLength;

        // Hide if we can't edit the name.
        if (!proto.CanCustomizeName)
        {
            RoleNameBox.Visible = false;
        }
        else
        {
            var name = loadout.EntityName;

            LoadoutNameLabel.Text = proto.NameDataset == null ?
                Loc.GetString("loadout-name-edit-label") :
                Loc.GetString("loadout-name-edit-label-dataset");

            RoleNameEdit.ToolTip = Loc.GetString(
                "loadout-name-edit-tooltip",
                ("max", _maxLoadoutNameLength));
            RoleNameEdit.Text = name ?? string.Empty;
            RoleNameEdit.OnTextChanged += args => OnNameChanged?.Invoke(args.Text);
        }

        // Frontier
        SearchBar.OnTextChanged += OnSearchTextChanged;
        // End Frontier

        // Hide if no groups
        if (proto.Groups.Count == 0)
        {
            LoadoutGroupsContainer.Visible = false;
            SearchContainer.Visible = false; // Frontier
            SetSize = Vector2.Zero;
        }
        else
        {
            foreach (var group in proto.Groups)
            {
                if (!protoManager.TryIndex(group, out var groupProto))
                    continue;

                if (groupProto.Hidden)
                    continue;

                var container = new LoadoutGroupContainer(profile, loadout, protoManager.Index(group), session, collection);
                LoadoutGroupsContainer.AddTab(container, Loc.GetString(groupProto.Name));
                _groups.Add(container);

                container.OnLoadoutPressed += args =>
                {
                    OnLoadoutPressed?.Invoke(group, args);
                };

                container.OnLoadoutUnpressed += args =>
                {
                    OnLoadoutUnpressed?.Invoke(group, args);
                };
            }

            // Frontier: VerticalTabContainer doesn't expose its tab buttons publicly,
            // so we reach into its XAML structure: ScrollContainer > PanelContainer > BoxContainer "TabContainer"
            if (_groups.Count > 0)
                _tabButtonContainer = LoadoutGroupsContainer.GetChild(0).GetChild(0).GetChild(0);
            // End Frontier
        }
        // Frontier: cost recalculated here and in RefreshLoadouts because loadout selection changes.
        CalculateLoadoutCost(loadout, collection);
        // Frontier: bank balance is static for the session, only set once.
        Balance.Margin = new Thickness(5, 2, 5, 5);
        Balance.Text = Loc.GetString("frontier-loadout-balance", ("balance", BankSystemExtensions.ToSpesoString(Profile.BankBalance)));
    }

    public void RefreshLoadouts(RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        foreach (var group in _groups)
        {
            group.RefreshLoadouts(Profile, loadout, session, collection);
        }

        CalculateLoadoutCost(loadout, collection); //Frontier
        ApplySearchFilter(); // Frontier: RefreshLoadouts rebuilds children, reapply filter
    }

    // Frontier
    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;
        ApplySearchFilter();
    }

    private void ApplySearchFilter()
    {
        var hasSearch = !string.IsNullOrEmpty(_searchText);

        for (var i = 0; i < _groups.Count; i++)
        {
            _groups[i].FilterLoadouts(_searchText);

            // Prevent users from switching to tabs with zero search results
            if (_tabButtonContainer != null
                && i < _tabButtonContainer.ChildCount
                && _tabButtonContainer.GetChild(i) is BaseButton button)
            {
                button.Disabled = hasSearch && !_groups[i].HasVisibleLoadouts();
            }
        }
    }
    // End Frontier

    /// <summary>
    /// Frontier function to calculate and update the label.
    /// </summary>
    /// <param name="loadout">The currently selected loadout</param>
    /// <param name="collection">IDependency Collection of various dependencies</param>
    private void CalculateLoadoutCost(RoleLoadout loadout, IDependencyCollection collection)
    {
        var protoManager = collection.Resolve<IPrototypeManager>();
        var cost = 0;
        foreach (var loadoutGroup in loadout.SelectedLoadouts)
        {
            foreach (var equipment in loadoutGroup.Value)
            {
                if (protoManager.TryIndex(equipment.Prototype, out var equipProto))
                {
                    cost += equipProto.Price;
                }
            }
        }

        Cost.Margin = new Thickness(5, 2, 5, 5);
        Cost.Text = Loc.GetString("frontier-loadout-cost", ("cost", BankSystemExtensions.ToSpesoString(cost)));
    }
    // End Frontier
}
