using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.CryoSleep;

[GenerateTypedNameReferences]
public sealed partial class AcceptCryoWindow : DefaultWindow
{
    public Action? OnAccept;
    public Action? OnDeny;
    public AcceptCryoWindow()
    {
        RobustXamlLoader.Load(this);
        AcceptButton.OnPressed += _ => OnAccept?.Invoke();
        DenyButton.OnPressed += _ => OnDeny?.Invoke();
    }
}
