# Tabs

- type: quickPhrase
  id: BaseCommonPhrase
  tab: Common Phrases
  abstract: true

- type: quickPhrase
  id: BaseJobPhrase
  tab: Jobs
  abstract: true

- type: quickPhrase
  id: BaseLocationPhrase
  tab: Locations
  abstract: true

- type: quickPhrase
  id: BaseSubjectPhrase
  tab: Subjects
  abstract: true

- type: quickPhrase
  id: BaseThreatPhrase
  tab: Safety
  abstract: true

- type: quickPhrase
  id: BaseSpeciesPhrase
  tab: Species
  abstract: true

# Location Specific

- type: quickPhrase
  id: BaseShuttleLocationPhrase
  tab: Shuttles
  group: Shuttles
  abstract: true

# Departments

- type: quickPhrase
  id: BaseCivilianPhrase
  group: Civilian
  abstract: true

- type: quickPhrase
  id: BaseCommandPhrase
  group: Command
  styleClass: CommandButton
  abstract: true

- type: quickPhrase
  id: BaseEngineeringPhrase
  group: Engineering
  styleClass: EngineeringButton
  abstract: true

- type: quickPhrase
  id: BaseJusticePhrase
  group: Justice
  styleClass: JusticeButton
  abstract: true

- type: quickPhrase
  id: BaseLogisticsPhrase
  group: Logistics
  styleClass: LogisticsButton
  abstract: true

- type: quickPhrase
  id: BaseMedicalPhrase
  group: Medical
  styleClass: MedicalButton
  abstract: true

- type: quickPhrase
  id: BaseSecurityPhrase
  group: Security
  styleClass: SecurityButton
  abstract: true

- type: quickPhrase
  id: BaseNFSDPhrase
  group: NFSD Outpost
  styleClass: SecurityButton
  abstract: true

- type: quickPhrase
  id: BaseStationPhrase
  group: Station
  styleClass: ServiceButton
  abstract: true

- type: quickPhrase
  id: BaseSciencePhrase
  group: Science
  styleClass: ScienceButton
  abstract: true

- type: quickPhrase
  id: BaseServicePhrase
  group: Service
  styleClass: ServiceButton
  abstract: true

# Wildcard

- type: quickPhrase
  id: BaseWildcardPhrase
  group: Wildcard
  abstract: true
