using Content.Shared._NF.Chemistry.Components;
using Content.Shared._NF.Chemistry.Events;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.Reagent;
using FastAccessors;
using Microsoft.CodeAnalysis;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NF.Chemistry.UI;

/// <summary>
///     A window that allows you to change the whitelist of the associated injector
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ChangeReagentWhitelistWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly EntityUid _injectorEntity;
    private readonly ChangeReagentWhitelistBoundUserInterface _owner;
    private ReagentPrototype? _selectedReagent;

    public ChangeReagentWhitelistWindow(ChangeReagentWhitelistBoundUserInterface owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _injectorEntity = owner.Owner;
        _owner = owner;

        // For debuging purposes only, replace before merging
        Title = "Reagent Filter";

        ReagentList.OnItemSelected += ReagentListSelected;
        ReagentList.OnItemDeselected += ReagentListDeselected;
        SearchBar.OnTextChanged += (_) => UpdateReagentPrototypes(SearchBar.Text);
        AddButton.OnPressed += ChangeWhitelistedReagent;

        UpdateReagentPrototypes();
        UpdateAddButton();
    }

    /// <summary>
    ///     Execute a console command that asks the server to add the selected reagent.
    /// </summary>
    private void ChangeWhitelistedReagent(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedReagent == null)
            return;

        _owner.ChangeReagentWhitelist(_selectedReagent);

    }

    private void ReagentListSelected(ItemList.ItemListSelectedEventArgs obj)
    {
        _selectedReagent = (ReagentPrototype) obj.ItemList[obj.ItemIndex].Metadata!;
        UpdateAddButton();
    }

    private void ReagentListDeselected(ItemList.ItemListDeselectedEventArgs obj)
    {
        _selectedReagent = null;
        UpdateAddButton();
    }

    /// <summary>
    ///     Set the Text and enabled/disabled status of the button that actually adds the reagent.
    /// </summary>
    private void UpdateAddButton()
    {
        AddButton.Disabled = true;
        if (_selectedReagent == null)
        {
            AddButton.Text = Loc.GetString("admin-add-reagent-window-add-invalid-reagent");
            return;
        }

        AddButton.Text = Loc.GetString("admin-add-reagent-window-add",
            ("reagent", _selectedReagent.ID));

        AddButton.Disabled = false;
    }

    /// <summary>
    ///     Get a list of all applicable reagent prototypes and show them in an item list.
    /// </summary>
    private void UpdateReagentPrototypes(string? filter = null)
    {
        ReagentList.Clear();

        List<string> allowedReagentGroups = new();
        if (_entityManager.TryGetComponent<ReagentWhitelistChangeComponent>(_injectorEntity, out var reagentWhitelistChangeComp))
        {
            allowedReagentGroups = reagentWhitelistChangeComp.AllowedReagentGroups;
        }


        foreach (var reagent in _prototypeManager.EnumeratePrototypes<ReagentPrototype>())
        {
            if (!string.IsNullOrEmpty(filter) &&
                !reagent.ID.ToLowerInvariant().Contains(filter.Trim().ToLowerInvariant()))
            {
                continue;
            }

            if (!allowedReagentGroups.Contains(reagent.Group))
            {
                continue;
            }

            ItemList.Item regentItem = new(ReagentList)
            {
                Metadata = reagent,
                Text = reagent.ID
            };

            ReagentList.Add(regentItem);
        }
    }
}

