using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared._NF.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using Content.Shared.FixedPoint;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Content.Client.Chemistry.UI;

namespace Content.Client._NF.Chemistry.UI
{
    /// <summary>
    /// Client-side UI used to control a <see cref="ChemPrenticeBoundUserInterfaceState"/>
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class ChemPrenticeWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototype = default!;
        public event Action<BaseButton.ButtonEventArgs, ReagentButton>? OnReagentButtonPressed;

        /// <summary>
        /// Create and initialize the chem master UI client-side. Creates the basic layout,
        /// actual data isn't filled in until the server sends data about the chem master.
        /// </summary>
        public ChemPrenticeWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        private ReagentButton MakeReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
        {
            var button = new ReagentButton(text, amount, id, isBuffer, styleClass);
            button.OnPressed += args
                => OnReagentButtonPressed?.Invoke(args, button);
            return button;
        }

        /// <summary>
        /// Update the UI state when new state data is received from the server.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ChemPrenticeBoundUserInterfaceState)state;
            UpdatePanelInfo(castState);

            //BufferCurrentVolume.Text = $" {castState.BufferCurrentVolume?.Int() ?? 0}u";

            InputEjectButton.Disabled = castState.InputContainerInfo is null;

        }

        /// <summary>
        /// Update the container, buffer, and packaging panels.
        /// </summary>
        /// <param name="state">State data for the dispenser.</param>
        private void UpdatePanelInfo(ChemPrenticeBoundUserInterfaceState state)
        {
            BufferTransferButton.Pressed = state.Mode == ChemMasterMode.Transfer;
            BufferDiscardButton.Pressed = state.Mode == ChemMasterMode.Discard;

            BuildContainerUI(InputContainerInfo, state.InputContainerInfo, true);

            BufferInfo.Children.Clear();

            if (!state.BufferReagents.Any())
            {
                BufferInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });

                return;
            }

            var bufferHBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal
            };
            BufferInfo.AddChild(bufferHBox);

            var bufferLabel = new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " };
            bufferHBox.AddChild(bufferLabel);
            var bufferVol = new Label
            {
                Text = $"{state.BufferCurrentVolume}/{state.BufferMaxVolume}",
                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
            };
            bufferHBox.AddChild(bufferVol);

            foreach (var (reagent, quantity) in state.BufferReagents.OrderBy(x => x.Reagent.Prototype)) // Frontier: add OrderBy
            {
                // Try to get the prototype for the given reagent. This gives us its name.
                _prototype.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");

                if (proto != null)
                {
                    BufferInfo.Children.Add(new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        Children =
                        {
                            new Label {Text = $"{name}: "},
                            new Label
                            {
                                Text = $"{quantity}u",
                                StyleClasses = {StyleNano.StyleClassLabelSecondaryColor}
                            },

                            // Padding
                            new Control {HorizontalExpand = true},

                            MakeReagentButton("1", ChemMasterReagentAmount.U1, reagent, true, StyleBase.ButtonOpenRight),
                            MakeReagentButton("5", ChemMasterReagentAmount.U5, reagent, true, StyleBase.ButtonOpenBoth),
                            MakeReagentButton("10", ChemMasterReagentAmount.U10, reagent, true, StyleBase.ButtonOpenBoth),
                            MakeReagentButton("25", ChemMasterReagentAmount.U25, reagent, true, StyleBase.ButtonOpenBoth),
                            MakeReagentButton("50", ChemMasterReagentAmount.U50, reagent, true, StyleBase.ButtonOpenBoth),
                            MakeReagentButton("100", ChemMasterReagentAmount.U100, reagent, true, StyleBase.ButtonOpenBoth),
                            MakeReagentButton(Loc.GetString("chem-master-window-buffer-all-amount"), ChemMasterReagentAmount.All, reagent, true, StyleBase.ButtonOpenLeft),
                        }
                    });
                }
            }
        }

        private void BuildContainerUI(Control control, ContainerInfo? info, bool addReagentButtons)
        {
            control.Children.Clear();

            if (info is null)
            {
                control.Children.Add(new Label
                {
                    Text = Loc.GetString("chem-master-window-no-container-loaded-text")
                });
            }
            else
            {
                // Name of the container and its fill status (Ex: 44/100u)
                control.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        new Label {Text = $"{info.DisplayName}: "},
                        new Label
                        {
                            Text = $"{info.CurrentVolume}/{info.MaxVolume}",
                            StyleClasses = {StyleNano.StyleClassLabelSecondaryColor}
                        }
                    }
                });

                IEnumerable<(string Name, ReagentId Id, FixedPoint2 Quantity)> contents;

                if (info.Entities != null)
                {
                    contents = info.Entities.Select(x => (x.Id, default(ReagentId), x.Quantity));
                }
                else if (info.Reagents != null)
                {
                    contents = info.Reagents.Select(x =>
                    {
                        _prototype.TryIndex(x.Reagent.Prototype, out ReagentPrototype? proto);
                        var name = proto?.LocalizedName
                                   ?? Loc.GetString("chem-master-window-unknown-reagent-text");

                        return (name, Id: x.Reagent, x.Quantity);
                    })
                        .OrderBy(r => r.Item1);
                }
                else
                {
                    return;
                }


                foreach (var (name, id, quantity) in contents)
                {
                    var inner = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        Children =
                        {
                            new Label { Text = $"{name}: " },
                            new Label
                            {
                                Text = $"{quantity}u",
                                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                            }
                        }
                    };

                    if (addReagentButtons)
                    {
                        var cs = inner.Children;

                        // Padding
                        cs.Add(new Control { HorizontalExpand = true });

                        cs.Add(MakeReagentButton(
                            "1", ChemMasterReagentAmount.U1, id, false, StyleBase.ButtonOpenRight));
                        cs.Add(MakeReagentButton(
                            "5", ChemMasterReagentAmount.U5, id, false, StyleBase.ButtonOpenBoth));
                        cs.Add(MakeReagentButton(
                            "10", ChemMasterReagentAmount.U10, id, false, StyleBase.ButtonOpenBoth));
                        cs.Add(MakeReagentButton(
                            "25", ChemMasterReagentAmount.U25, id, false, StyleBase.ButtonOpenBoth));
                        cs.Add(MakeReagentButton(
                            "50", ChemMasterReagentAmount.U50, id, false, StyleBase.ButtonOpenBoth));
                        cs.Add(MakeReagentButton(
                            "100", ChemMasterReagentAmount.U100, id, false, StyleBase.ButtonOpenBoth));
                        cs.Add(MakeReagentButton(
                            Loc.GetString("chem-master-window-buffer-all-amount"),
                            ChemMasterReagentAmount.All, id, false, StyleBase.ButtonOpenLeft));
                    }

                    control.Children.Add(inner);
                }

            }
        }
    }
}
