using System.Numerics;
using Content.Client.Paper.UI;
using Content.Shared._NF.Paper;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.RichText;
using Content.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using static Content.Shared.Paper.PaperComponent;
using static Content.Shared._NF.Paper.PaperBundleComponent;

namespace Content.Client._NF.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class PaperBundleWindow : BaseWindow
{
    [Dependency] private readonly IInputManager _inputManager = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    private static readonly Color DefaultTextColor = new(25, 25, 25);

    private const int DragMarginSize = 16;

    /// <summary>
    /// Reference to the paper content texture so we can modify it in Draw().
    /// </summary>
    private StyleBoxTexture _paperContentTex = new();

    /// <summary>
    /// Number of lines that the content image represents.
    /// See PaperVisualsComponent.ContentImageNumLines.
    /// </summary>
    private float _paperContentLineScale = 1.0f;

    /// <summary>
    /// Tracks which resize directions are allowed (may be restricted by per-page visuals).
    /// </summary>
    private DragMode _allowedResizeModes = ~DragMode.None;

    private readonly Type[] _allowedTags =
    [
        typeof(BoldItalicTag),
        typeof(BoldTag),
        typeof(BulletTag),
        typeof(ColorTag),
        typeof(HeadingTag),
        typeof(ItalicTag),
        typeof(MonoTag)
    ];

    /// <summary>
    /// Fired when the user saves text on a page. Carries (pageEntity, text).
    /// </summary>
    public event Action<NetEntity, string>? OnSaved;

    private List<BundlePageData> _pages = new();
    private int _currentPage;

    /// <summary>
    /// Maximum text length for the current page, from PaperComponent.ContentSize.
    /// </summary>
    private int _maxInputLength = 10000;

    public PaperBundleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        BlankPaperIndicator.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, DefaultTextColor);

        CloseButton.OnPressed += _ => Close();

        PrevPageButton.OnPressed += _ =>
        {
            if (_currentPage > 0)
            {
                _currentPage--;
                PopulatePage(_currentPage);
            }
        };

        NextPageButton.OnPressed += _ =>
        {
            if (_currentPage < _pages.Count - 1)
            {
                _currentPage++;
                PopulatePage(_currentPage);
            }
        };

        Input.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
            {
                if (!SaveButton.Disabled)
                {
                    RunOnSaved();
                    args.Handle();
                }
            }
        };

        Input.OnTextChanged += _ =>
        {
            UpdateFillState();
        };

        SaveButton.OnPressed += _ =>
        {
            RunOnSaved();
        };

        SaveButton.Text = Loc.GetString("paper-ui-save-button",
            ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));
    }

    /// <summary>
    /// Populates the window with all page data from the BUI state.
    /// </summary>
    public void Populate(PaperBundleBoundUserInterfaceState state)
    {
        _pages = state.Pages;

        // If any page is in write mode, navigate to it (the last page)
        var writePage = -1;
        for (var i = 0; i < _pages.Count; i++)
        {
            if (_pages[i].Mode == PaperAction.Write)
            {
                writePage = i;
                break;
            }
        }

        if (writePage >= 0)
            _currentPage = writePage;
        else if (_currentPage >= _pages.Count)
            _currentPage = Math.Max(0, _pages.Count - 1);

        PopulatePage(_currentPage);
    }

    /// <summary>
    /// Renders the specified page's content, stamps, visuals, and mode.
    /// </summary>
    private void PopulatePage(int index)
    {
        _currentPage = index;
        UpdateNavigation();

        if (index < 0 || index >= _pages.Count)
        {
            // No pages to display
            WrittenTextLabel.Visible = false;
            BlankPaperIndicator.Visible = true;
            InputContainer.Visible = false;
            EditButtons.Visible = false;
            StampDisplay.RemoveAllChildren();
            StampDisplay.RemoveStamps();
            return;
        }

        var page = _pages[index];

        // Apply per-page visuals from the page entity's PaperVisualsComponent
        InitPageVisuals(page);

        var isEditing = page.Mode == PaperAction.Write;

        InputContainer.Visible = isEditing;
        EditButtons.Visible = isEditing;

        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(page.Text);

        // Pad for stamps so they don't overlap text
        if (page.StampedBy.Count > 0)
        {
            for (var i = 0; i < 6; i++)
                msg.AddMarkupPermissive("\r\n");
        }

        WrittenTextLabel.SetMessage(msg, _allowedTags, DefaultTextColor);

        WrittenTextLabel.Visible = !isEditing && page.Text.Length > 0;
        BlankPaperIndicator.Visible = !isEditing && page.Text.Length == 0;

        _maxInputLength = page.ContentSize;

        if (isEditing)
        {
            Input.TextRope = Rope.Leaf.Empty;
            Input.CursorPosition = new TextEdit.CursorPos();
            Input.InsertAtCursor(page.Text);
            UpdateFillState();
        }

        // Render stamps
        StampDisplay.RemoveAllChildren();
        StampDisplay.RemoveStamps();
        StampDisplay.PlacementSeed = (int)_entMan.GetEntity(page.PageEntity);
        foreach (var stamp in page.StampedBy)
        {
            StampDisplay.AddStamp(new StampWidget { StampInfo = stamp });
        }
    }

    /// <summary>
    /// Applies per-page visual styling by looking up PaperVisualsComponent on the page entity.
    /// Replicates the logic from PaperWindow.InitVisuals().
    /// </summary>
    private void InitPageVisuals(BundlePageData page)
    {
        // Reset to defaults before applying new visuals
        _allowedResizeModes = ~DragMode.None;
        _paperContentTex = new StyleBoxTexture();
        _paperContentLineScale = 1.0f;
        PaperBackground.ModulateSelfOverride = null;
        PaperBackground.PanelOverride = null;
        HeaderImage.TextureNormal = null;
        HeaderImage.MinSize = Vector2.Zero;
        HeaderImage.ModulateSelfOverride = null;
        HeaderImage.Margin = default;
        FooterImage.TextureNormal = null;
        FooterImage.MinSize = Vector2.Zero;
        FooterImage.ModulateSelfOverride = null;
        FooterImage.Margin = default;
        PaperContent.ModulateSelfOverride = null;
        PaperContent.PanelOverride = null;
        PaperContent.Margin = default;
        WrittenTextLabel.ModulateSelfOverride = null;
        FillStatus.ModulateSelfOverride = null;
        TextAlignmentPadding.Margin = default;

        var pageUid = _entMan.GetEntity(page.PageEntity);
        if (!_entMan.TryGetComponent<PaperVisualsComponent>(pageUid, out var visuals))
            return;

        // Randomize stamp placement based on entity UID
        StampDisplay.PlacementSeed = (int)pageUid;

        // Background
        PaperBackground.ModulateSelfOverride = visuals.BackgroundModulate;
        var backgroundImage = visuals.BackgroundImagePath != null
            ? _resCache.GetResource<TextureResource>(visuals.BackgroundImagePath)
            : null;
        if (backgroundImage != null)
        {
            var backgroundImageMode = visuals.BackgroundImageTile
                ? StyleBoxTexture.StretchMode.Tile
                : StyleBoxTexture.StretchMode.Stretch;
            var backgroundPatchMargin = visuals.BackgroundPatchMargin;
            PaperBackground.PanelOverride = new StyleBoxTexture
            {
                Texture = backgroundImage,
                TextureScale = visuals.BackgroundScale,
                Mode = backgroundImageMode,
                PatchMarginLeft = backgroundPatchMargin.Left,
                PatchMarginBottom = backgroundPatchMargin.Bottom,
                PatchMarginRight = backgroundPatchMargin.Right,
                PatchMarginTop = backgroundPatchMargin.Top
            };
        }

        // Header
        if (visuals.HeaderImagePath != null)
        {
            HeaderImage.TexturePath = visuals.HeaderImagePath;
            HeaderImage.MinSize = HeaderImage.TextureNormal?.Size ?? Vector2.Zero;
        }

        HeaderImage.ModulateSelfOverride = visuals.HeaderImageModulate;
        HeaderImage.Margin = new Thickness(visuals.HeaderMargin.Left, visuals.HeaderMargin.Top,
            visuals.HeaderMargin.Right, visuals.HeaderMargin.Bottom);

        // Footer
        if (visuals.FooterImagePath is { } footerPath)
        {
            FooterImage.TexturePath = footerPath.ToString();
            FooterImage.MinSize = FooterImage.TextureNormal?.Size ?? Vector2.Zero;
        }

        FooterImage.ModulateSelfOverride = visuals.FooterImageModulate;
        FooterImage.Margin = new Thickness(visuals.FooterMargin.Left, visuals.FooterMargin.Top,
            visuals.FooterMargin.Right, visuals.FooterMargin.Bottom);

        // Content area
        PaperContent.ModulateSelfOverride = visuals.ContentImageModulate;
        WrittenTextLabel.ModulateSelfOverride = visuals.FontAccentColor;
        FillStatus.ModulateSelfOverride = visuals.FontAccentColor;

        var contentImage = visuals.ContentImagePath != null
            ? _resCache.GetResource<TextureResource>(visuals.ContentImagePath)
            : null;
        if (contentImage != null)
        {
            _paperContentTex = new StyleBoxTexture
            {
                Texture = contentImage,
                Mode = StyleBoxTexture.StretchMode.Tile,
            };
            PaperContent.PanelOverride = _paperContentTex;
            _paperContentLineScale = visuals.ContentImageNumLines;
        }

        PaperContent.Margin = new Thickness(
            visuals.ContentMargin.Left, visuals.ContentMargin.Top,
            visuals.ContentMargin.Right, visuals.ContentMargin.Bottom);

        // Max writable area constraints
        if (visuals.MaxWritableArea != null)
        {
            var a = (Vector2)visuals.MaxWritableArea;
            ScrollingContents.MinSize = Vector2.Zero;
            ScrollingContents.MinSize = a;

            if (a.X > 0.0f)
            {
                ScrollingContents.MaxWidth = a.X;
                _allowedResizeModes &= ~(DragMode.Left | DragMode.Right);
                SetWidth = float.NaN;
            }

            if (a.Y > 0.0f)
            {
                ScrollingContents.MaxHeight = a.Y;
                _allowedResizeModes &= ~(DragMode.Top | DragMode.Bottom);
                SetHeight = float.NaN;
            }
        }
    }

    /// <summary>
    /// Syncs the paper content texture tiling with the font line height.
    /// Replicates the logic from PaperWindow.Draw().
    /// </summary>
    protected override void Draw(DrawingHandleScreen handle)
    {
        if (WrittenTextLabel.TryGetStyleProperty<Font>("font", out var font))
        {
            var fontLineHeight = font.GetLineHeight(1.0f);
            _paperContentTex.ExpandMarginTop = font.GetDescent(UIScale);
            var scaleY = (_paperContentLineScale * fontLineHeight) / _paperContentTex.Texture?.Height ?? fontLineHeight;
            _paperContentTex.TextureScale = new Vector2(1, scaleY);

            // Adjust text alignment padding to sync with content image lines
            {
                var headerHeight = HeaderImage.Size.Y + HeaderImage.Margin.Top + HeaderImage.Margin.Bottom;
                var headerInLines = headerHeight / (fontLineHeight * _paperContentLineScale);
                var paddingRequiredInLines = (float)Math.Ceiling(headerInLines) - headerInLines;
                var verticalMargin = fontLineHeight * paddingRequiredInLines * _paperContentLineScale;
                TextAlignmentPadding.Margin = new Thickness(0.0f, verticalMargin, 0.0f, 0.0f);
            }
        }

        base.Draw(handle);
    }

    private void UpdateNavigation()
    {
        PrevPageButton.Disabled = _currentPage <= 0;
        NextPageButton.Disabled = _currentPage >= _pages.Count - 1;

        PageIndicator.Text = Loc.GetString("paper-bundle-page-indicator",
            ("current", _currentPage + 1),
            ("total", _pages.Count));
    }

    private void RunOnSaved()
    {
        if (_currentPage < 0 || _currentPage >= _pages.Count)
            return;

        SaveButton.Disabled = true;
        OnSaved?.Invoke(_pages[_currentPage].PageEntity, Rope.Collapse(Input.TextRope));
    }

    private void UpdateFillState()
    {
        var inputLength = Input.TextLength;

        FillStatus.Text = Loc.GetString("paper-ui-fill-level",
            ("currentLength", inputLength),
            ("maxLength", _maxInputLength));

        SaveButton.Disabled = inputLength > _maxInputLength;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.None;

        if (relativeMousePos.Y < DragMarginSize)
            mode |= DragMode.Top;
        else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            mode |= DragMode.Bottom;

        if (relativeMousePos.X < DragMarginSize)
            mode |= DragMode.Left;
        else if (relativeMousePos.X > Size.X - DragMarginSize)
            mode |= DragMode.Right;

        if ((mode & _allowedResizeModes) == DragMode.None)
            return DragMode.Move;

        return mode & _allowedResizeModes;
    }
}
