using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class NFCargoPalletMenu : FancyWindow
{
    public Action? SellRequested;
    public Action? AppraiseRequested;

    public NFCargoPalletMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
        AppraiseButton.OnPressed += OnAppraisePressed;
    }

    public void UpdateValues(
        int amount,
        int count,
        float modifier,
        int modifierSpesos,
        int total)
    {
        AppraisalLabel.Text = BankSystemExtensions.ToSpesoString(amount);
        CountLabel.Text = count.ToString();

        var modifierPercentage = (modifier - 1.0) * 100;
        if (modifier > 1.0)
        {
            ModifierLabel.Text = Loc.GetString("cargo-pallet-menu-modifier-label-positive");
            ModifierRateLabel.Text = Loc.GetString(
                "cargo-pallet-menu-modifier-rate-label-positive",
                ("modifier", modifierPercentage));
            ModifierRateLabel.Visible = true;
        }
        else if (modifier < 1.0)
        {
            ModifierLabel.Text = Loc.GetString("cargo-pallet-menu-modifier-label-negative");
            ModifierRateLabel.Text = Loc.GetString(
                "cargo-pallet-menu-modifier-rate-label-negative",
                ("modifier", -modifierPercentage));
            ModifierRateLabel.Visible = true;
        }
        else
        {
            ModifierLabel.Text = Loc.GetString("cargo-pallet-menu-modifier-label-neutral");
            ModifierRateLabel.Visible = false;
        }

        ModifierValueLabel.Text = BankSystemExtensions.ToSpesoString(modifierSpesos);
        TotalLabel.Text = BankSystemExtensions.ToSpesoString(total);
        // Re-layout the table in case the displayed values need a different amount of space than before (items added or
        // removed)
        AppraisalContainer.InvalidateMeasure();
    }

    public void SetEnabled(bool enabled)
    {
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs obj)
    {
        AppraiseRequested?.Invoke();
    }
}
