using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.ShuttleRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleRecordDetailsControl : PanelContainer
{
    public sealed class ViewState(string shuttleName, string shuttleOwnerName, string activity, string toolTip, string timeOfPurchase)
    {
        public string ShuttleName { get; } = shuttleName;

        public string ShuttleOwnerName { get; } = shuttleOwnerName;

        public string Activity { get; } = activity;

        public string ToolTip { get; } = toolTip;

        public string TimeOfPurchase { get; } = timeOfPurchase;
    }

    public ShuttleRecordDetailsControl(ViewState state)
    {
        RobustXamlLoader.Load(this);
        ShuttleName.Text = state.ShuttleName;
        ShuttleOwner.Text = state.ShuttleOwnerName;
        ShuttleActivity.Text = state.Activity;
        TimeOfPurchase.SetMarkup(state.TimeOfPurchase);
        ToolTip = state.ToolTip;
    }
}
