- type: entity
  id: CauldronDeepFryerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: spooky cauldron machine board
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenDeepFryerCauldron
      requirements:
        Capacitor: 1
        MatterBin: 1 
      stackRequirements:
        Steel: 4
        Glass: 2
        Cable: 5
      tagRequirements:
        PlushieGhost:
         amount: 1
         defaultPrototype: PlushieGhost
    - type: Tag
      tags:
      - FlatpackerBlacklist
    - type: Construction
      deconstructionTarget: null
      graph: FryerBoard
      node: spookyfryer