blank_issues_enabled: true
contact_links:
  - name: Request a Feature
    url: https://discord.gg/tpuAT7d3zm/
    about: Submit feature requests on our Discord server (https://discord.gg/tpuAT7d3zm/).
