using Content.Client.Message;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Content.Client.CartridgeLoader.Cartridges.NF_ShipConnectUi;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NF_ShipConnectUiFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<bool>? OnSync;
    private NF_ShipConnectPage _currentPage;
    private List<NF_ShipConnectPage>? _pages;

    public NF_ShipConnectUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _pages = new List<NF_ShipConnectPage>(_prototypeManager.EnumeratePrototypes<NF_ShipConnectPage>());

        _currentPage = FindPageById("mainmenu");//ISSUE SOMEWHERE HERE
        UpdateUI(_currentPage);

        StartButton.OnPressed += _ => UpdateUI(FindPageById(FindPageById("mainmenu").OnStart!));
        HomeButton.OnPressed += _ => UpdateUI(FindPageById("mainmenu"));
        YesButton.OnPressed += _ => AdvanceState(_currentPage!, true);
        NoButton.OnPressed += _ => AdvanceState(_currentPage!, false);
    }

    public void AdvanceState(NF_ShipConnectPage currentPage, bool yesPressed)
    {
        UpdateUI(yesPressed ? FindPageById(currentPage.OnYes!) : FindPageById(currentPage.OnNo!));
    }

    public void UpdateUI(NF_ShipConnectPage page)
    {
        _currentPage = page;
        bool isResult = page.LocKeyPunishment != null;

        StartButton.Visible = page.OnStart != null;
        YesButton.Visible = page.OnYes != null;
        NoButton.Visible = page.OnNo != null;
        HomeButton.Visible = page.OnStart == null;
        Explanation.Visible = page.OnStart == null;

        Subtitle.Visible = page.LocKeySeverity != null;
        Punishment.Visible = page.LocKeyPunishment != null;

        if (!isResult)
        {
            string question = $"\n[font size=15]{Loc.GetString(page.LocKey!)}[/font]";

            if (question.ToLower().Contains("sophont"))
            {
                string sophontExplanation = Loc.GetString("crime-assist-sophont-explanation");
                question += $"\n[font size=8][color=#999999]{sophontExplanation}[/color][/font]";
            }

            Title.SetMarkup(question);
            Subtitle.SetMarkup(string.Empty);
            Explanation.SetMarkup(string.Empty);
            Punishment.SetMarkup(string.Empty);
        }
        else
        {
            string color = page.LocKeySeverity! switch
            {
                "crime-assist-crimetype-innocent" => "#39a300",
                "crime-assist-crimetype-misdemeanour" => "#7b7b30",
                "crime-assist-crimetype-felony" => "#7b5430",
                "crime-assist-crimetype-capital" => "#7b2e30",
                _ => "#ff00ff"
            };

            Title.SetMarkup("\n[bold][font size=23][color=#a4885c]" + Loc.GetString(page.LocKeyTitle!) + "[/color][/font][/bold]");
            Subtitle.SetMarkup($"\n[font size=19][color={color}]" + Loc.GetString(page.LocKeySeverity!) + "[/color][/font]");
            Explanation.SetMarkup("\n[title]" + Loc.GetString(page.LocKeyDescription!) + "[/title]\n");
            Punishment.SetMarkup("[bold][font size=15]" + Loc.GetString(page.LocKeyPunishment!) + "[/font][/bold]");
        }
    }

    private NF_ShipConnectPage FindPageById(string id)
    {
        return _pages?.Find(o => o.ID == id)!;
    }
}
