using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Client._NF.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class CrewPickerWindow : FancyWindow
{

}
