using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Controls;
using Content.Shared.Players.PlayTimeTracking;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._NF.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class NFLateJoinGui : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IConsoleHost _consoleHost = default!;
    [Dependency] private readonly JobRequirementsManager _jobReqs = default!;
    [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private ClientGameTicker _gameTicker;
    private ISawmill _latejoinSawmill;

    private NetEntity _lastSelection;

    private readonly Dictionary<string, NewFrontierLateJoinJobButton> _buttons = new();

    public NFLateJoinGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        _gameTicker.LobbyJobsAvailableUpdated += UpdateUi;
        _latejoinSawmill = Logger.GetSawmill("latejoin");
        VesselSelection.VesselItemList.OnItemSelected += args =>
        {
            UpdateUi(_gameTicker.JobsAvailable);
        };
        CrewManifestButton.OnPressed += _ =>
        {
            EntitySystem.Get<CrewManifestSystem>().RequestCrewManifest(_lastSelection);
        };

        _lastSelection = _gameTicker.JobsAvailable.Keys.FirstOrNull() ?? NetEntity.Invalid;

        UpdateUi(_gameTicker.JobsAvailable);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _gameTicker.LobbyJobsAvailableUpdated -= UpdateUi;
    }

    public void UpdateUi(IReadOnlyDictionary<NetEntity, Dictionary<ProtoId<JobPrototype>, int?>> obj)
    {
        var currentCharacter = _preferencesManager.Preferences?.SelectedCharacter;
        if (VesselSelection.Selected is null ||
            currentCharacter is null ||
            currentCharacter is not HumanoidCharacterProfile humanoidCharacter)
        {
            CrewManifestButton.Visible = false;
            foreach (var (_, button) in _buttons)
            {
                JobList.RemoveChild(button);
            }
            _buttons.Clear();
            return;
        }

        CrewManifestButton.Visible = true;

        var station = VesselSelection.Selected.Value;
        var jobs = obj[station];

        if (station != _lastSelection)
        {
            foreach (var (_, button) in _buttons)
            {
                JobList.RemoveChild(button);
            }
            _buttons.Clear();
        }

        _lastSelection = station;

        foreach (var (jobId, _) in jobs)
        {
            if (_buttons.ContainsKey(jobId))
                continue;

            var job = _prototypeManager.Index<JobPrototype>(jobId);

            var newButton = new NewFrontierLateJoinJobButton(station, jobId, _gameTicker, _prototypeManager, _jobReqs, _preferencesManager);
            newButton.OnPressed += args =>
            {
                _latejoinSawmill.Info($"Late joining as ID: {jobId}");
                _consoleHost.ExecuteCommand($"joingame {CommandParsing.Escape(jobId)} {station}");
                Close();
            };

            if (!_jobReqs.IsAllowed(job, humanoidCharacter, out var denyReason))
            {
                newButton.Disabled = true;
                newButton.ToolTip = denyReason?.ToString() ?? "";
            }

            JobList.AddChild(newButton);

            _buttons.Add(jobId, newButton);
        }

    }
}
