using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class StationOrCrewPickerWindow : FancyWindow
{
    public StationOrCrewPickerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StationButton.OnPressed += StationButtonOnOnPressed;
        CrewButton.OnPressed += CrewButtonOnOnPressed;
    }

    private void StationButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        new PickerWindow(PickerWindow.PickerType.Station).OpenCentered();
        Close();
    }

    private void CrewButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        new PickerWindow(PickerWindow.PickerType.Crew).OpenCentered();
        Close();
    }
}
