- type: quickPhrase
  id: BaseSecuritySubjectPhrase
  parent: [ BaseSubjectPhrase, BaseSecurityPhrase ]
  abstract: true

- type: quickPhrase
  id: HandcuffsPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-handcuffs

- type: quickPhrase
  id: ZiptiesPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-zipties

- type: quickPhrase
  id: StunBatonPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-stun-baton

- type: quickPhrase
  id: DisablerPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-disabler

- type: quickPhrase
  id: FlashPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-flash

- type: quickPhrase
  id: FlashbangPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-flashbang

- type: quickPhrase
  id: TeargasPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-teargas

- type: quickPhrase
  id: StingerPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-stinger

- type: quickPhrase
  id: BarrierPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-barrier

- type: quickPhrase
  id: BelligerentPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-belligerent

- type: quickPhrase
  id: ForeignPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-foreign

- type: quickPhrase
  id: DemeritPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-demerit

- type: quickPhrase
  id: ArrestPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-arrest

- type: quickPhrase
  id: FinePhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-fine

- type: quickPhrase
  id: CitationPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-citation

- type: quickPhrase
  id: WarrantPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-warrant

- type: quickPhrase
  id: ReportPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-report

- type: quickPhrase
  id: PermitPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-permit

- type: quickPhrase
  id: SearchPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-search

- type: quickPhrase
  id: DetainPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-detain

- type: quickPhrase
  id: InterrogatePhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-interrogate

- type: quickPhrase
  id: SuspectPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-suspect

- type: quickPhrase
  id: wantedPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-wanted

- type: quickPhrase
  id: ReasonableSuspicionPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-reasonable-suspicion

- type: quickPhrase
  id: ProbableCausePhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-probable-cause

- type: quickPhrase
  id: ExcigentCircumstancesPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-excigent-circumstances

- type: quickPhrase
  id: ForensicScannerPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-forensic-scanner

- type: quickPhrase
  id: ForensicPadPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-forensic-pad

- type: quickPhrase
  id: LogProbePhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-log-probe

- type: quickPhrase
  id: ReleasePhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-release

- type: quickPhrase
  id: ParolePhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-parole

- type: quickPhrase
  id: BolaPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-bola

- type: quickPhrase
  id: AfterActionPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-after-action

- type: quickPhrase
  id: ContrabandPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-contraband

- type: quickPhrase
  id: TurnoverPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-turnover

- type: quickPhrase
  id: lawPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-law

- type: quickPhrase
  id: NFZPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-nfz

- type: quickPhrase
  id: sopPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-sop

- type: quickPhrase
  id: PrincipalPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-principal

- type: quickPhrase
  id: SolicitationPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-solicitation

- type: quickPhrase
  id: AccessoryPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-accessory

- type: quickPhrase
  id: AttemptPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-attempt

- type: quickPhrase
  id: ConspiracyPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-conspiracy

- type: quickPhrase
  id: DuressPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-duress

- type: quickPhrase
  id: EntrapmentPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-entrapment

- type: quickPhrase
  id: RecidivismPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-recidivism

- type: quickPhrase
  id: AggravationPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-aggravation

- type: quickPhrase
  id: DemotionPhrase
  parent: BaseSecuritySubjectPhrase
  text: phrase-demotion
