- type: quickPhrase
  id: BaseServiceSubjectPhrase
  parent: [ BaseSubjectPhrase, BaseServicePhrase ]
  abstract: true

- type: quickPhrase
  id: MeatPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-meat

- type: quickPhrase
  id: FlourPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-flour

- type: quickPhrase
  id: RicePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-rice

- type: quickPhrase
  id: DoughPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-dough

- type: quickPhrase
  id: BreadPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bread

- type: quickPhrase
  id: MilkPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-milk

- type: quickPhrase
  id: PilkPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-pilk

- type: quickPhrase
  id: CoffeePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-coffee

- type: quickPhrase
  id: TeaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-tea

- type: quickPhrase
  id: EggPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-egg

- type: quickPhrase
  id: WheatPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-wheat

- type: quickPhrase
  id: VegetablePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-vegetable

- type: quickPhrase
  id: FruitPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-fruit

- type: quickPhrase
  id: SugarPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-sugar

- type: quickPhrase
  id: AlcoholPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-alcohol

- type: quickPhrase
  id: NonAlcoholicPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-non-alcoholic

- type: quickPhrase
  id: JuicePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-juice

- type: quickPhrase
  id: MopPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-mop

- type: quickPhrase
  id: BucketPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bucket

- type: quickPhrase
  id: SpaceCleanerPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-space-cleaner

- type: quickPhrase
  id: SoapPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-soap

- type: quickPhrase
  id: TrashPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-trash

- type: quickPhrase
  id: StagePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-stage

- type: quickPhrase
  id: SeedPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-seed

- type: quickPhrase
  id: PlantPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-plant

- type: quickPhrase
  id: MutagenPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-mutagen

- type: quickPhrase
  id: RobustPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-robust

- type: quickPhrase
  id: WeedPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-weed

- type: quickPhrase
  id: KnifePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-knife

- type: quickPhrase
  id: MicrowavePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-microwave

- type: quickPhrase
  id: GrillPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-grill

- type: quickPhrase
  id: SavoryPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-savory

- type: quickPhrase
  id: SweetPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-sweet

- type: quickPhrase
  id: SaltyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-salty

- type: quickPhrase
  id: SourPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-sour

- type: quickPhrase
  id: BitterPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bitter

- type: quickPhrase
  id: SpicyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-spicy

- type: quickPhrase
  id: MetallicPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-metallic

- type: quickPhrase
  id: MeatyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-meaty

- type: quickPhrase
  id: FishyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-fishy

- type: quickPhrase
  id: CrabbyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-crabby

- type: quickPhrase
  id: CheesyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cheesy

- type: quickPhrase
  id: FunnyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-funny

- type: quickPhrase
  id: StrangePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-strange

- type: quickPhrase
  id: TinglyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-tingly

- type: quickPhrase
  id: AcidPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-acid

- type: quickPhrase
  id: LeafyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-leafy

- type: quickPhrase
  id: MintyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-minty

- type: quickPhrase
  id: NuttyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-nutty

- type: quickPhrase
  id: ChalkyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-chalky

- type: quickPhrase
  id: OilyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-oily

- type: quickPhrase
  id: PepperyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-peppery

- type: quickPhrase
  id: SlimyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-slimy

- type: quickPhrase
  id: MagicalPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-magical

- type: quickPhrase
  id: FiberPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-fiber

- type: quickPhrase
  id: ColdPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cold

- type: quickPhrase
  id: SpookyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-spooky

- type: quickPhrase
  id: SmokeyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-smokey

- type: quickPhrase
  id: FruityPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-fruity

- type: quickPhrase
  id: CreamyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-creamy

- type: quickPhrase
  id: FizzyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-fizzy

- type: quickPhrase
  id: ShockingPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-shocking

- type: quickPhrase
  id: CheapPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cheap

- type: quickPhrase
  id: PiquantPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-piquant

- type: quickPhrase
  id: SharpPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-sharp

- type: quickPhrase
  id: SyrupyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-syrupy

- type: quickPhrase
  id: SpaceshroomPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-spaceshroom

- type: quickPhrase
  id: CleanPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-clean

- type: quickPhrase
  id: AlkalinePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-alkaline

- type: quickPhrase
  id: HolyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-holy

- type: quickPhrase
  id: HorriblePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-horrible

- type: quickPhrase
  id: TerriblePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-terrible

- type: quickPhrase
  id: MindfulPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-mindful

- type: quickPhrase
  id: ChewyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-chewy

- type: quickPhrase
  id: TrashyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-trashy

- type: quickPhrase
  id: MotivatingPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-motivating

- type: quickPhrase
  id: UnknownPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-unknown

- type: quickPhrase
  id: NutritionPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-nutrition

- type: quickPhrase
  id: VitaminPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-vitamin

- type: quickPhrase
  id: ProteinPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-protein

- type: quickPhrase
  id: TomatoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-tomato

- type: quickPhrase
  id: PotatoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-potato

- type: quickPhrase
  id: OnionPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-onion

- type: quickPhrase
  id: AloePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-aloe

- type: quickPhrase
  id: PoppyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-poppy

- type: quickPhrase
  id: GalaxyThistlePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-galaxythistle

- type: quickPhrase
  id: MeatwheatPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-meatwheat

- type: quickPhrase
  id: OatPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-oat

- type: quickPhrase
  id: BananaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-banana

- type: quickPhrase
  id: MimanaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-mimana

- type: quickPhrase
  id: CarrotPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-carrot

- type: quickPhrase
  id: CabbagePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cabbage

- type: quickPhrase
  id: GarlicPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-garlic

- type: quickPhrase
  id: LemonPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-lemon

- type: quickPhrase
  id: LimePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-lime

- type: quickPhrase
  id: OrangePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-orange

- type: quickPhrase
  id: ExtOrangePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-extradimensional-orange

- type: quickPhrase
  id: PineapplePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-pineapple

- type: quickPhrase
  id: SugarcanePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-sugarcane

- type: quickPhrase
  id: TeaplantPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-teaplant

- type: quickPhrase
  id: PapercanePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-papercane

- type: quickPhrase
  id: TowercapPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-towercap

- type: quickPhrase
  id: SteelcapPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-steelcap

- type: quickPhrase
  id: BlueTomatoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bluetomato

- type: quickPhrase
  id: BloodTomatoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bloodtomato

- type: quickPhrase
  id: KillerTomatoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-killertomato

- type: quickPhrase
  id: EggplantPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-eggplant

- type: quickPhrase
  id: EggyPlantPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-eggyplant

- type: quickPhrase
  id: ApplePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-apple

- type: quickPhrase
  id: GoldenApplePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-goldenapple

- type: quickPhrase
  id: CornPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-corn

- type: quickPhrase
  id: OnionRedPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-onionred

- type: quickPhrase
  id: ChanterellePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-chanterelle

- type: quickPhrase
  id: CannabisPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cannabis

- type: quickPhrase
  id: RainbowCannabisPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-rainbowcannabis

- type: quickPhrase
  id: TobaccoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-tobacco

- type: quickPhrase
  id: NettlePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-nettle

- type: quickPhrase
  id: DeathNettlePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-deathnettle

- type: quickPhrase
  id: ChiliPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-chili

- type: quickPhrase
  id: ChillyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-chilly

- type: quickPhrase
  id: LaughinPeaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-laughinpea

- type: quickPhrase
  id: LilyPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-lily

- type: quickPhrase
  id: LingzhiPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-lingzhi

- type: quickPhrase
  id: AmbrosiaVulgarisPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-ambrosiavulgaris

- type: quickPhrase
  id: AmbrosiadeusPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-ambrosiadeus

- type: quickPhrase
  id: GlasstlePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-glasstle

- type: quickPhrase
  id: FlyAmanitaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-flyamanita

- type: quickPhrase
  id: GatFruitPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-gatfruit

- type: quickPhrase
  id: SoybeanPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-soybean

- type: quickPhrase
  id: SpacemanTrumpetPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-spacemantrumpet

- type: quickPhrase
  id: KoibeanPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-koibean

- type: quickPhrase
  id: WatermelonPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-watermelon

- type: quickPhrase
  id: HolymelonPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-holymelon

- type: quickPhrase
  id: GrapePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-grape

- type: quickPhrase
  id: CocoaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cocoa

- type: quickPhrase
  id: BerriesPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-berries

- type: quickPhrase
  id: BungoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bungo

- type: quickPhrase
  id: PeaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-pea

- type: quickPhrase
  id: WorldPeaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-worldpea

- type: quickPhrase
  id: PumpkinPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-pumpkin

- type: quickPhrase
  id: BluePumpkinPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bluepumpkin

- type: quickPhrase
  id: CottonPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cotton

- type: quickPhrase
  id: PyrottonPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-pyrotton

- type: quickPhrase
  id: CherryPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cherry

- type: quickPhrase
  id: AnomalyBerryPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-anomalyberry

- type: quickPhrase
  id: BloonionPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bloonion

- type: quickPhrase
  id: GoldLeafPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-goldleaf

- type: quickPhrase
  id: PearPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-pear

- type: quickPhrase
  id: AvocadoPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-avocado

- type: quickPhrase
  id: CucumberPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cucumber

- type: quickPhrase
  id: BeesPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-bees

- type: quickPhrase
  id: EveryspicePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-everyspice

- type: quickPhrase
  id: MonkananaPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-monkanana

- type: quickPhrase
  id: GlowshroomPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-glowshroom

- type: quickPhrase
  id: PomegranatePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-pomegranate

- type: quickPhrase
  id: GranatapfelPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-granatapfel

- type: quickPhrase
  id: LemoonPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-lemoon

- type: quickPhrase
  id: EZNutrientPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-eznutrient
