using Content.Shared.StationBounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentListEntry : Control
{
    public event Action<BountyContract>? OnRemoveButtonPressed;

    public BountyContractUiFragmentListEntry(BountyContract contract, bool canRemoveContracts)
    {
        RobustXamlLoader.Load(this);

        BountyName.Text = contract.Name;

        // vessel
        var vessel = contract.Vessel ?? Loc.GetString("bounty-contracts-ui-create-vesel-unknown");
        var vesselMsg = Loc.GetString("bounty-contracts-ui-list-vesel", ("vessel", vessel));
        BountyVessel.Text = vesselMsg;

        // bounty description
        var desc = contract.Description ?? Loc.GetString("bounty-contracts-ui-list-no-description");
        BountyDescription.SetMessage(desc);

        // author
        if (!string.IsNullOrEmpty(contract.Author))
        {
            var author = Loc.GetString("bounty-contracts-ui-list-author", ("author", contract.Author));
            BountyAuthor.Text = author;
        }

        // bounty reward
        BountyReward.Text = Loc.GetString("cargo-console-menu-points-amount",
            ("amount", contract.Reward.ToString()));

        // remove button
        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke(contract);
        RemoveButton.Disabled = !canRemoveContracts;
    }
}
