using Content.Client.UserInterface.Controls;
using Content.Shared.StationBounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.StationBounties.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractMenu : FancyWindow
{
    public BountyContractMenu()
    {
        RobustXamlLoader.Load(this);

        /*BountiesContainer.AddChild(new StationBountyMenuEntry("Cuban Pete - Dead or Alive",
            "They call me Cuban Pete. I'm the king of the rumba beat. When I play the maracas I go chick-chicky-boom, chick-chicky boom",
            10000, "Alan Poe (Head of Security)")
        );
        BountiesContainer.AddChild(new StationBountyMenuEntry("Bar Lonely Carp - Open",
            "Cord: (100, 200) - first drink is free!!!!!",
            0, "Joe Doe (Captain)")
        );
        BountiesContainer.AddChild(new StationBountyMenuEntry("Buying artifacts",
            "For science!",
            5000, "Joe Doe II (Scientist)")
        );

        CreateMenu.SetPossibleTargets(new List<BountyContractTargetInfo>
        {
            new() {Name = "Bill", DNA = "ACGTGCA"},
            new() {Name = "Joe Doe", DNA = "GTTCCAA"},
            new() {Name = "Alan Poe", DNA = "ACGGGTAACC"},
            new() {Name = "George Clinton", DNA = "CCCGGGTTAA"},
            new() {Name = "Cuban Pete", DNA = "AAACGGGTTTAA"}
        });


        CreateMenu.SetVessels(new List<string>()
        {
            "NT-16 324",
            "NT-32 123",
            "NT-324 3212",
            "NT-23 324",
            "NT-16 12"
        });*/
    }
}
