using Content.Shared.StationBounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentListEntry : Control
{
    public BountyContractUiFragmentListEntry(BountyContract contract)
    {
        RobustXamlLoader.Load(this);

        BountyName.Text = contract.Name;

        // vessel
        var vessel = Loc.GetString("bounty-contracts-ui-list-vesel", ("vessel", contract.Vessel));
        BountyVessel.Text = vessel;

        // bounty description
        var desc = contract.Description;
        if (string.IsNullOrEmpty(contract.Description))
            desc = Loc.GetString("bounty-contracts-ui-list-no-description");
        BountyDescription.SetMessage(desc);

        // bounty reward
        BountyReward.Text = Loc.GetString("cargo-console-menu-points-amount",
            ("amount", contract.Reward.ToString()));
    }
}
