using Content.Shared.StationBounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentList : Control
{
    public event Action? OnCreateButtonPressed;

    public BountyContractUiFragmentList()
    {
        RobustXamlLoader.Load(this);
        CreateButton.OnPressed += _ => OnCreateButtonPressed?.Invoke();
    }

    public void SetContracts(List<BountyContract> listStateContracts)
    {
        BountiesContainer.RemoveAllChildren();

        if (listStateContracts.Count == 0)
        {
            NoContractsLabel.Visible = true;
            return;
        }

        NoContractsLabel.Visible = false;
        foreach (var contract in listStateContracts)
        {
            BountiesContainer.AddChild(new BountyContractUiFragmentListEntry(contract));
        }

    }
}
