// SPDX-FileCopyrightText: 2025 jhrushbe <capnmerry@gmail.com>
// SPDX-FileCopyrightText: 2025 rottenheadphones <juaelwe@outlook.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: CC-BY-NC-SA-3.0

using System.Diagnostics.CodeAnalysis;
using System.IO;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Power.Generation.FissionGenerator;
using Content.Shared.Atmos;
using Content.Shared.Ghost.Roles;
using Content.Shared.Lock;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Power.UI;

/// <summary>
/// Client-side UI used to view a nuclear reactor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NuclearReactorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = null!;
    private readonly LockSystem _lock;

    private readonly Dictionary<Vector2i, StyleBoxFlat> _reactorGrid = [];
    private readonly Dictionary<Vector2i, TextureRect> _reactorRect = [];
    private readonly Dictionary<Vector2i, Button> _reactorButton = [];

    private readonly StyleBoxFlat _temperatureBar = new(Color.Black);
    private readonly StyleBoxFlat _radiationBar = new(Color.Black);
    private readonly StyleBoxFlat _powerBar = new(Color.Black);

    private Dictionary<Vector2i, ReactorSlotBUIData> _data = [];
    private int _gridWidth = 0;
    private int _gridHeight = 0;

    private byte _displayMode = 1<<0;

    private enum DisplayModes : byte
    {
        Temperature = 1 << 0,
        Neutron = 1 << 1,
        Target = 1 << 2,
        Fuel = 1 << 3
    }

    private byte _temperatureMode = 1 << 0;

    private enum TemperatureModes : byte
    {
        Celcius = 1 << 0,
        Kelvin = 1 << 1,
        // Fahrenheit = 1 << 2
    }

    private int _targetX = 0;
    private int _targetY = 0;

    public event Action<Vector2d>? ItemActionButtonPressed;
    public event Action? EjectButtonPressed;

    public event Action<float>? ControlRodModify;

    private EntityUid _reactor;

    private bool _isMonitor = false;
    private EntityUid _monitor;

    private readonly float _repeatDelay = 0.5f;
    private readonly Dictionary<Button, float> _repeatQueue = [];

    public NuclearReactorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lock = _entityManager.System<LockSystem>();

        ReactorTempBar.ForegroundStyleBoxOverride = _temperatureBar;
        ReactorRadsBar.ForegroundStyleBoxOverride = _radiationBar;
        ReactorThermBar.ForegroundStyleBoxOverride = _powerBar;

        ChangeViewButton.OnPressed += _ => OnChangeViewButtonPressed();
        XIncrement.OnPressed += _ => MoveTarget(1, 0);
        XDecrement.OnPressed += _ => MoveTarget(-1, 0);
        YIncrement.OnPressed += _ => MoveTarget(0, 1);
        YDecrement.OnPressed += _ => MoveTarget(0, -1);
        ItemAction.OnPressed += _ => ItemActionButtonPressed?.Invoke(new(_targetY, _targetX));
        EjectItem.OnPressed += _ => EjectButtonPressed?.Invoke();

        ControlRodsInsertLarge.OnPressed += _ => AdjustControlRods(0.1f);
        ControlRodsInsertLarge.OnButtonDown += _ => _repeatQueue.Add(ControlRodsInsertLarge, _repeatDelay);
        ControlRodsInsertLarge.OnButtonUp += _ => _repeatQueue.Remove(ControlRodsInsertLarge);

        ControlRodsInsert.OnPressed += _ => AdjustControlRods(0.01f);
        ControlRodsInsert.OnButtonDown += _ => _repeatQueue.Add(ControlRodsInsert, _repeatDelay);
        ControlRodsInsert.OnButtonUp += _ => _repeatQueue.Remove(ControlRodsInsert);

        ControlRodsRemove.OnPressed += _ => AdjustControlRods(-0.01f);
        ControlRodsRemove.OnButtonDown += _ => _repeatQueue.Add(ControlRodsRemove, _repeatDelay);
        ControlRodsRemove.OnButtonUp += _ => _repeatQueue.Remove(ControlRodsRemove);

        ControlRodsRemoveLarge.OnPressed += _ => AdjustControlRods(-0.1f);
        ControlRodsRemoveLarge.OnButtonDown += _ => _repeatQueue.Add(ControlRodsRemoveLarge, _repeatDelay);
        ControlRodsRemoveLarge.OnButtonUp += _ => _repeatQueue.Remove(ControlRodsRemoveLarge);

        TargetTemperature.OnPressed += _ => ChangeTemp();
    }

    public void Update(NuclearReactorBuiState msg)
    {
        _data = msg.SlotData;

        ReactorTempValue.Text = FormatTemperature(msg.ReactorTemp);
        ReactorTempBar.Value = msg.ReactorTemp;
        _temperatureBar.BackgroundColor = GetColor(Atmospherics.T20C, ReactorTempBar.MaxValue * 0.75, msg.ReactorTemp);

        ReactorRadsValue.Text = msg.ReactorRads <= msg.ReactorRadsMax ? Math.Round(msg.ReactorRads, 1).ToString() : "OVERLOAD";
        ReactorRadsBar.Value = msg.ReactorRads;
        _radiationBar.BackgroundColor = GetColor(0, ReactorRadsBar.MaxValue * 0.5, msg.ReactorRads);

        ReactorThermValue.Text = FormatPower(msg.ReactorTherm);
        ReactorThermBar.Value = msg.ReactorTherm;
        _powerBar.BackgroundColor = GetSteppedColor(ReactorThermBar.MaxValue * 0.75, ReactorThermBar.MaxValue, msg.ReactorTherm);

        ControlRodsValue.Text = Math.Round(msg.ControlRodActual * 50, 1).ToString() + "%";
        ControlRodsActual.Value = msg.ControlRodActual;
        ControlRodsSet.Value = msg.ControlRodSet;

        var locktarget = _isMonitor ? _monitor : _reactor;

        ControlRodsButtons.Visible = !_lock.IsLocked(locktarget);
        ItemAction.Visible = !_lock.IsLocked(_reactor) && !_isMonitor;

        ItemActionLock.Visible = _lock.IsLocked(_reactor) && !_isMonitor;
        ControlRodsLock.Visible = _lock.IsLocked(locktarget);

        Shelf.Visible = !_isMonitor;

        ItemName.Text = msg.ItemName ?? "empty";
    }

    public void SetEntity(EntityUid reactor, EntityUid? monitor = null)
    {
        _reactor = reactor;

        if (monitor != null)
        {
            _monitor = monitor.Value;
            _isMonitor = true;
        }

        this.SetInfoFromEntity(_entityManager, _isMonitor ? _monitor : _reactor);

        if (!_entityManager.TryGetComponent<NuclearReactorComponent>(_reactor, out var reactorComponent))
            return;

        _gridWidth = reactorComponent.ReactorGridWidth;
        _gridHeight = reactorComponent.ReactorGridHeight;

        ReactorGrid.Columns = _gridWidth;

        ReactorTempBar.MaxValue = reactorComponent.ReactorMeltdownTemp;
        ReactorRadsBar.MaxValue = reactorComponent.MaximumRadiation;
        ReactorThermBar.MaxValue = reactorComponent.MaximumThermalPower;

        InitReactorGrid();
    }

    public void InitReactorGrid()
    {
        for (var x = 0; x < _gridWidth; x++)
        {
            for (var y = 0; y < _gridHeight; y++)
            {
                var styleBox = new StyleBoxFlat();
                var icon = new TextureRect()
                {
                    SetSize = new(32, 32),
                    TexturePath = "/Textures/_FarHorizons/Structures/Power/Generation/FissionGenerator/reactor_part_inserted/base.png"
                };
                var button = new Button
                {
                    Margin = new(0),
                    StyleBoxOverride = new StyleBoxFlat(Color.Transparent),
                    ToolTip = "",
                    TooltipDelay = 0.5f
                };

                var vect = new Vector2i(x, y);
                _reactorGrid.Add(vect, styleBox);
                _reactorRect.Add(vect, icon);
                _reactorButton.Add(vect, button);

                var control = new PanelContainer
                {
                    Margin = new Thickness(2),
                    PanelOverride = styleBox,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };
                control.AddChild(button);
                var nvect = new Vector2i(y, x); // Can't be declared as a part of the line below for some reason, will break if you try
                button.OnPressed += _ => SetTarget(nvect);
                button.AddChild(icon);
                ReactorGrid.AddChild(control);
            }
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        //Update the grid
        for (var x = 0; x < _gridWidth; x++)
        {
            for (var y = 0; y < _gridHeight; y++)
            {
                var vect = new Vector2i(x, y);
                var exists = _data.ContainsKey(vect);
                var box = _reactorGrid[vect];
                switch (_displayMode)
                {
                    case (byte)DisplayModes.Temperature:
                        box.BackgroundColor = GetColor(293.15, 1200, exists ? _data[vect].Temperature : 0);
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-temp");
                        break;
                    case (byte)DisplayModes.Neutron:
                        box.BackgroundColor = GetColor(0, 7, exists ? _data[vect].NeutronCount : 0);
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-neutron");
                        break;
                    case (byte)DisplayModes.Target:
                        box.BackgroundColor = y == _targetX && x == _targetY ? Color.Yellow : Color.Gray;
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-target");
                        break;
                    case (byte)DisplayModes.Fuel:
                        box.BackgroundColor = Color.InterpolateBetween(Color.Gray, Color.FromHex("#22bbff"), exists && _data[vect].SpentFuel > 0 ? (float)GetFuelLevel(_data[vect]) : 0);
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-fuel");
                        break;
                }

                var icon = exists ? _data[vect].IconName : "base";
                _reactorRect[vect].TexturePath = "/Textures/_FarHorizons/Structures/Power/Generation/FissionGenerator/reactor_part_inserted/" +  icon + ".png";

                _reactorButton[vect].ToolTip = exists && _data[vect].SpentFuel > 0
                    ? "Fuel Level: " + (int)Math.Round(GetFuelLevel(_data[vect]) * 100) + "%"
                    : "";
            }
        }

        UpdateTargetInfo();
        UpdateItemAction();

        // Handle repeat buttons
        foreach ( var kvp in _repeatQueue)
        {
            if(kvp.Value > 0)
            {
                _repeatQueue[kvp.Key] -= args.DeltaSeconds;
                continue;
            }

            switch (kvp.Key)
            {
                case var _ when kvp.Key == ControlRodsInsertLarge:
                    AdjustControlRods(0.1f);
                    break;
                case var _ when kvp.Key == ControlRodsInsert:
                    AdjustControlRods(0.01f);
                    break;
                case var _ when kvp.Key == ControlRodsRemove:
                    AdjustControlRods(-0.01f);
                    break;
                case var _ when kvp.Key == ControlRodsRemoveLarge:
                    AdjustControlRods(-0.1f);
                    break;
            }
        }
    }

    private static Color GetColor(double pointA, double pointB, double value)
    {
        var mid = pointA+((pointB-pointA) / 2);
        Color result;

        if (value < pointA && pointA > 0)
            result = Color.InterpolateBetween(Color.DarkBlue, Color.FromHex("#31843E"), (float)(value / pointA));
        else if (value >= pointA && value < mid)
            result = Color.InterpolateBetween(Color.FromHex("#31843E"), Color.FromHex("#BBBB00"), (float)((value - pointA) / (mid - pointA)));
        else if (value >= mid && value < pointB)
            result = Color.InterpolateBetween(Color.FromHex("#BBBB00"), Color.FromHex("#BB3232"), (float)((value - mid) / (pointB - mid)));
        else if (value >= pointB && value < pointB * 1.4)
            result = Color.InterpolateBetween(Color.FromHex("#BB3232"), Color.FromHex("#550000"), (float)((value - pointB) / ((pointB * 1.4) - pointB)));
        else if (value >= pointB * 1.4)
            result = Color.FromHex("#550000"); // Death.
        else
            result = Color.Black;

        return result;
    }

    private static Color GetSteppedColor(double pointA, double pointB, double value)
    {
        Color result;

        if (value > pointB)
            result = Color.FromHex("#BB3232");
        else if (value > pointA)
            result = Color.FromHex("#BBBB00");
        else
            result = Color.FromHex("#31843E");

        return result;
    }

    private void OnChangeViewButtonPressed()
    {
        // The bits go marching one by one...
        _displayMode <<= 1;
        if (_displayMode >= 1 << Enum.GetNames<DisplayModes>().Length)
            _displayMode = 1 << 0;
    }

    private void ChangeTemp()
    {
        _temperatureMode <<= 1;
        if (_temperatureMode >= 1 << Enum.GetNames<TemperatureModes>().Length)
            _temperatureMode = 1 << 0;
    }

    private string FormatTemperature(double temperature) => _temperatureMode switch
    {
        (byte)TemperatureModes.Celcius => Math.Round(temperature - Atmospherics.T0C, 1).ToString() + "C",
        (byte)TemperatureModes.Kelvin => Math.Round(temperature, 1).ToString() + "K",
        // (byte)TemperatureModes.Fahrenheit => Math.Round(((temperature - Atmospherics.T0C) * 9 / 5) + 32, 1).ToString() + "F",
        _ => "NaN",
    };

    private void UpdateTargetInfo()
    {
        var vect = new Vector2i(_targetY,  _targetX);
        if(!_data.TryGetValue(vect, out var value))
        {
            TargetName.Text = "empty";
            TargetTemperatureGrid.Visible = TargetNRadiationGrid.Visible = TargetRadiationGrid.Visible = TargetSpentGrid.Visible = false;
            return;
        }

        TargetName.Text = value.PartName;

        TargetTemperatureGrid.Visible = value.Temperature > 0;
        TargetTemperature.Text = FormatTemperature(value.Temperature);

        TargetNRadiationGrid.Visible = value.NeutronRadioactivity > 0;
        TargetNRadiation.Text = Math.Round(value.NeutronRadioactivity, 2).ToString();

        TargetRadiationGrid.Visible = value.Radioactivity > 0;
        TargetRadiation.Text = Math.Round(value.Radioactivity, 2).ToString();

        TargetSpentGrid.Visible = value.SpentFuel > 0;
        TargetSpent.Text = Math.Round(value.SpentFuel, 2).ToString();
    }

    private void UpdateItemAction()
    {
        if(ItemName.Text == "empty" == (TargetName.Text == "empty"))
        {
            ItemAction.Disabled = true;
            return;
        }
        else
            ItemAction.Disabled = false;

        ItemAction.Text = TargetName.Text != "empty"
            ? Loc.GetString("comp-nuclear-reactor-ui-remove-button")
            : Loc.GetString("comp-nuclear-reactor-ui-insert-button");
    }

    private void MoveTarget(int x, int y) => SetTarget(_targetX + x, _targetY + y);

    private void SetTarget(Vector2i vect) => SetTarget(vect.X, vect.Y);

    private void SetTarget(int x, int y)
    {
        _targetX = Math.Clamp(x, 0, _gridWidth - 1);
        _targetY = Math.Clamp(y, 0, _gridHeight - 1);

        TargetPos.Text = _targetX.ToString() +"," + _targetY.ToString();

        XIncrement.Disabled = _targetX >= _gridWidth - 1;
        XDecrement.Disabled = _targetX <= 0;
        YIncrement.Disabled = _targetY >= _gridHeight - 1;
        YDecrement.Disabled = _targetY <= 0;
    }

    public void SetItemName(string? itemName) => ItemName.Text = itemName ?? "empty";

    private static string FormatPower(float power) => Loc.GetString("comp-nuclear-reactor-ui-therm-format", ("power", power));

    private static double GetFuelLevel(ReactorSlotBUIData data) => Math.Max(1 - (data.SpentFuel / (data.SpentFuel + (data.Radioactivity * 0.5) + (data.NeutronRadioactivity * 0.25))), 0);

    private void AdjustControlRods(float amount) => ControlRodModify?.Invoke(amount);
}
