using System.Linq;
using Content.Client.GameTicking.Managers;
using Content.Client.UserInterface.Controls;
using Content.Shared.GameTicking;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.Utility;

namespace Content.Client._NF.LateJoin.Windows;

[GenerateTypedNameReferences]
public sealed partial class PickerWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IConsoleHost _consoleHost = default!;
    private readonly ClientGameTicker _gameTicker;
    private readonly ISawmill _sawmill;

    public enum PickerType
    {
        StationOrCrewLarge,
        Crew,
        Station,
    }

    private PickerType _currentTab;
    private readonly Controls.StationOrCrewLargeControl _stationOrCrewLargeControl = new();
    private readonly Controls.CrewPickerControl _crewPickerControl = new();
    private readonly Controls.StationPickerControl _stationPickerControl = new();

    /**
     * Default constructors without arguments are mandatory for RobustXamlLoader
     */
    public PickerWindow() : this(PickerType.Station) { }

    public PickerWindow(PickerType currentTab)
    {
        _currentTab = currentTab;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        _gameTicker.LobbyJobsAvailableUpdated += UpdateUi;
        _sawmill = Logger.GetSawmill("latejoin");

        CrewTabButton.OnPressed += _ =>
        {
            _currentTab = PickerType.Crew;
            UpdateUi(_gameTicker.StationJobInformationList);
        };

        StationTabButton.OnPressed += _ =>
        {
            _currentTab = PickerType.Station;
            UpdateUi(_gameTicker.StationJobInformationList);
        };

        _stationPickerControl.OnJobJoined += (stationEntity, jobId) =>
        {
            _sawmill.Info($"Late joining as ID: {jobId}");
            _consoleHost.ExecuteCommand(
                $"joingame {CommandParsing.Escape(jobId)} {stationEntity}");

            Close();
        };

        UpdateUi(_gameTicker.StationJobInformationList);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _gameTicker.LobbyJobsAvailableUpdated -= UpdateUi;
    }

    private void UpdateUi(IReadOnlyDictionary<NetEntity, StationJobInformation> obj)
    {
        // This is the place where it filters out cargo stations and others that shouldn't be shown in the latejoin ui.
        var availableJobs = obj.Where(kvp => kvp.Value.JobsAvailable.Values.Count != 0)
            .ToDictionary(kvp => kvp.Key, kvp => kvp.Value);

        var stationJobs = availableJobs.Where(kvp => kvp.Value.IsLateJoinStation).ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
        var crewJobs = availableJobs.Where(kvp => !kvp.Value.IsLateJoinStation).ToDictionary(kvp => kvp.Key, kvp => kvp.Value);

        StationTabLabel.Text = _loc.GetString("frontier-lobby-station-title") + stationJobs.GetJobSumCountString();
        StationTabButton.Disabled = !StationJobInformationExtensions.IsAnyStationAvailable(availableJobs) || _currentTab == PickerType.Station;

        CrewTabLabel.Text = _loc.GetString("frontier-lobby-crew-title") + crewJobs.GetJobSumCountString();
        CrewTabButton.Disabled = !StationJobInformationExtensions.IsAnyCrewJobAvailable(availableJobs) || _currentTab == PickerType.Crew;

        ContentContainer.RemoveAllChildren();
        switch (_currentTab)
        {
            case PickerType.StationOrCrewLarge:
                ContentContainer.AddChild(_stationOrCrewLargeControl);
                // Set the tab change callback once.
                _stationOrCrewLargeControl.OnTabChange ??= tab => _currentTab = tab;
                break;
            case PickerType.Crew:
                ContentContainer.AddChild(_crewPickerControl);
                break;
            case PickerType.Station:
                ContentContainer.AddChild(_stationPickerControl);
                _stationPickerControl.UpdateUi(availableJobs);
                break;
            default:
                throw new ArgumentOutOfRangeException(); // This will never happen. Trust.
        }
    }
}
