- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackCentcom # Frontier
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcomcap # Frontier
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat # Frontier
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: BoxFolderCentComClipboard # Frontier
    pocket1: NFWeaponPistolN1984 # Frontier


- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
