using System.Linq;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility; // wizden#42210
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // wizden#42210
    private AudioSystem _audioSystem;

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;

    public event Action<bool>? OnRepeatToggled; // wizden#42210
    public event Action<bool>? OnShuffleToggled; // wizden#42210
    public event Action<ProtoId<JukeboxPrototype>>? TrackQueueAction; // wizden#42210
    public event Action<float>? SetTime;
    public event Action<int>? QueueDeleteAction; // wizden#42210
    public event Action<int>? QueueMoveUpAction; // wizden#42210
    public event Action<int>? QueueMoveDownAction; // wizden#42210

    private List<JukeboxPrototype> _availableTracks = new(); // wizden#42210
    private EntityUid? _audio;

    private float _lockTimer;

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        SearchBar.OnTextChanged += _ => // wizden#42210
        {
            PopulateTracklist(); // wizden#42210
        };

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += args =>
        {
            OnStopPressed?.Invoke();
        };

        RepeatButton.OnToggled += args => // wizden#42210
        {
            OnRepeatToggled?.Invoke(RepeatButton.Pressed); // wizden#42210
        };

        ShuffleButton.OnToggled += args => // wizden#42210
        {
            OnShuffleToggled?.Invoke(ShuffleButton.Pressed); // wizden#42210
        };

        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
    }

    public JukeboxMenu(AudioSystem audioSystem)
    {
        _audioSystem = audioSystem;
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    // wizden#42210
    public void PopulateTracklist()
    {
        var tracksToShow = new List<JukeboxPrototype>();
        foreach (var track in _availableTracks)
        {
            if (SearchBar.Text.Trim().Length != 0)
            {
                if (track.Name.ToLowerInvariant().Contains(SearchBar.Text.Trim().ToLowerInvariant()) || track.Artist.ToLowerInvariant().Contains(SearchBar.Text.Trim().ToLowerInvariant()))
                    tracksToShow.Add(track);
            }
            else
            {
                tracksToShow.Add(track);
            }
        }

        // Sort tracks by artist then track name
        var sortedTracksToShow = tracksToShow.OrderBy(track => track.Artist).ThenBy(track => track.Name);

        // Get the existing list of queue controls
        var oldChildCount = TrackList.ChildCount;

        int idx = 0;
        foreach (var prototype in sortedTracksToShow)
        {
            if (idx >= oldChildCount)
            {
                var control = new TrackListingControl(prototype);
                control.OnButtonPressed += s =>
                {
                    TrackQueueAction?.Invoke(s);
                };
                TrackList.AddChild(control);
            }
            else
            {
                var child = TrackList.GetChild(idx) as TrackListingControl;

                if (child == null)
                {
                    DebugTools.Assert($"Jukebox track listing control at {idx} is not of type TrackListingControl"); // Something's gone terribly wrong.
                    continue;
                }

                child.SetTrackInfo(prototype);
            }
            idx++;
        }

        // Shrink list if new list is shorter than old list.
        for (var childIdx = oldChildCount - 1; idx <= childIdx; childIdx--)
        {
            TrackList.RemoveChild(childIdx);
        }
    }


    /// <summary>
    /// Populates the queue list with all queued items
    /// </summary>
    /// <param name="queue"></param>
    public void PopulateQueueList(IReadOnlyCollection<ProtoId<JukeboxPrototype>> queue)
    {
        // Get the existing list of queue controls
        var oldChildCount = QueueList.ChildCount;

        var idx = 0;
        foreach (var item in queue)
        {
            var track = _prototypeManager.Index(item);

            if (idx >= oldChildCount)
            {
                var queuedTrackBox = new QueuedTrackControl(track, idx, idx == 0, idx == queue.Count - 1);
                queuedTrackBox.OnDeletePressed += s => QueueDeleteAction?.Invoke(s);
                queuedTrackBox.OnMoveUpPressed += s => QueueMoveUpAction?.Invoke(s);
                queuedTrackBox.OnMoveDownPressed += s => QueueMoveDownAction?.Invoke(s);

                QueueList.AddChild(queuedTrackBox);
            }
            else
            {
                var child = QueueList.GetChild(idx) as QueuedTrackControl;

                if (child == null)
                {
                    DebugTools.Assert($"Jukebox menu queued track control at {idx} is not of type QueuedTrackControl"); // Something's gone terribly wrong.
                    continue;
                }

                child.SetTrackInfo(track);
                child.SetIndex(idx);
                child.SetButtonStatus(idx == 0, idx == queue.Count - 1);
            }
            idx++;
        }

        // Shrink list if new list is shorter than old list.
        for (var childIdx = oldChildCount - 1; idx <= childIdx; childIdx--)
        {
            QueueList.RemoveChild(childIdx);
        }
    }
    // End wizden#42210

    public void UpdateAvailableTracks(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        _availableTracks = new();

        foreach (var entry in jukeboxProtos)
        {
            _availableTracks.Add(entry);
        }
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        if (playing)
        {
            PlayButton.Text = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayButton.Text = Loc.GetString("jukebox-menu-buttonplay");
    }

    // wizden#42210
    public void UpdateButtons(bool repeat, bool shuffle)
    {
        RepeatButton.Pressed = repeat;
        ShuffleButton.Pressed = shuffle;
    }

    public void SetSelectedSong(JukeboxPrototype? prototype, float length)
    {
        if (prototype is null)
        {
            CurrentlyPlaying.RemoveAllChildren();
        }
        else
        {
            if (CurrentlyPlaying.ChildCount != 0)
            {
                var child = CurrentlyPlaying.GetChild(0) as TrackListingControl;

                if (child is null)
                {
                    DebugTools.Assert("Jukebox menu currently playing control is not of type TrackListingControl"); // Something's gone terribly wrong.
                }
                else
                {
                    child.SetTrackInfo(prototype);
                }

            }
            else
            {
                var control = new TrackListingControl(prototype);
                CurrentlyPlaying.AddChild(control);
            }
        } // End wizden#42210
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = $"00:00 / 00:00";
        }

        if (PlaybackSlider.Grabbed)
            return;

        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
        {
            PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        }
        else
        {
            PlaybackSlider.SetValueWithoutEvent(0f);
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }
}