using System.Linq;
using System.Numerics;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

/// <summary>
/// UI class to handle the selection of a player's job priorities.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class JobPriorityEditor : BoxContainer
{
    private readonly IClientPreferencesManager _preferencesManager;
    private readonly IPrototypeManager _prototypeManager;
    private readonly JobRequirementsManager _requirements;

    private readonly Dictionary<string, BoxContainer> _jobCategories = new();
    private readonly List<(ProtoId<JobPrototype>, RequirementsSelector)> _jobPriorities = new();

    public Dictionary<ProtoId<JobPrototype>, JobPriority> SelectedJobPriorities { get; private set; } = new();

    public event Action<Dictionary<ProtoId<JobPrototype>, JobPriority>>? Save;

    public JobPriorityEditor(
        IClientPreferencesManager preferencesManager,
        IPrototypeManager prototypeManager,
        JobRequirementsManager requirements)
    {
        _prototypeManager = prototypeManager;
        _requirements = requirements;
        _preferencesManager = preferencesManager;
        RobustXamlLoader.Load(this);

        ResetButton.OnPressed += args =>
        {
            SelectedJobPriorities = _preferencesManager.Preferences?.JobPriorities.ShallowClone()
                ?? new Dictionary<ProtoId<JobPrototype>, JobPriority>();
            UpdateJobPriorities();
            CheckDirty();
        };

        SaveButton.OnPressed += args =>
        {
            Save?.Invoke(SelectedJobPriorities);
            UpdateJobPriorities();
            CheckDirty();
        };

        RefreshJobs();
    }

    public void RefreshJobs()
    {
        JobList.DisposeAllChildren();
        _jobCategories.Clear();
        _jobPriorities.Clear();
        var firstCategory = true;

        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>()
            .Where(dep => !dep.EditorHidden)
            .ToList();

        departments.Sort(DepartmentUIComparer.Instance);

        var selectorPriorities = new[]
        {
            ("humanoid-profile-editor-job-priority-never-button", (int) JobPriority.Never),
            ("humanoid-profile-editor-job-priority-low-button", (int) JobPriority.Low),
            ("humanoid-profile-editor-job-priority-medium-button", (int) JobPriority.Medium),
            ("humanoid-profile-editor-job-priority-high-button", (int) JobPriority.High),
        };

        foreach (var department in departments)
        {
            var departmentName = Loc.GetString(department.Name);

            if (!_jobCategories.TryGetValue(department.ID, out var category))
            {
                category = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    Name = department.ID,
                };

                if (firstCategory)
                {
                    firstCategory = false;
                }
                else
                {
                    category.AddChild(new Control
                    {
                        MinSize = new Vector2(0, 23),
                    });
                }

                category.AddChild(new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                    Children =
                    {
                        new Label
                        {
                            Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                ("departmentName", departmentName)),
                            Margin = new Thickness(5f, 0, 0, 0)
                        }
                    }
                });

                _jobCategories[department.ID] = category;
                JobList.AddChild(category);
            }

            var jobs = department.Roles.Select(jobId => _prototypeManager.Index(jobId))
                .Where(job => job.SetPreference)
                .ToList();

            jobs.Sort(JobUIComparer.Instance);

            foreach (var job in jobs)
            {
                var jobContainer = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                };

                var selector = new RequirementsSelector
                {
                    Margin = new Thickness(3f, 3f, 3f, 0f),
                };

                var icon = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center
                };
                var jobIcon = _prototypeManager.Index(job.Icon);
                icon.Texture = jobIcon.Icon.Frame0();
                selector.Setup(selectorPriorities, job.LocalizedName, 200, job.LocalizedDescription, icon, job.Guides);

                if (!_requirements.IsAllowed(job, null, out var reason))
                {
                    selector.LockRequirements(reason);
                    SelectedJobPriorities[job.ID] = JobPriority.Never;
                    CheckDirty();
                }
                else
                {
                    selector.UnlockRequirements();
                }

                selector.OnSelected += selectedPrio =>
                {
                    var selectedJobPrio = (JobPriority) selectedPrio;

                    SelectedJobPriorities[job.ID] = selectedJobPrio;

                    foreach (var (jobId, other) in _jobPriorities)
                    {
                        if (jobId == job.ID)
                        {
                            other.Select(selectedPrio);
                            continue;
                        }
                    }

                    CheckDirty();
                };

                _jobPriorities.Add((job.ID, selector));

                jobContainer.AddChild(selector);
                category.AddChild(jobContainer);
            }
        }

        SelectedJobPriorities = _preferencesManager.Preferences?.JobPriorities.ShallowClone()
            ?? new Dictionary<ProtoId<JobPrototype>, JobPriority>();
        UpdateJobPriorities();
        CheckDirty();
    }

    private void UpdateJobPriorities()
    {
        foreach (var (jobId, selector) in _jobPriorities)
        {
            var priority = SelectedJobPriorities.GetValueOrDefault(jobId, JobPriority.Never);
            selector.Select((int) priority);
        }
    }

    public void LoadJobPriorities()
    {
        SelectedJobPriorities = _preferencesManager.Preferences?.JobPriorities.ShallowClone()
            ?? new Dictionary<ProtoId<JobPrototype>, JobPriority>();
        UpdateJobPriorities();
        CheckDirty();
    }

    private void CheckDirty()
    {
        var dirty = IsDirty();
        SaveButton.Disabled = !dirty;
        ResetButton.Disabled = !dirty;
    }

    public bool IsDirty()
    {
        foreach (var (jobId, selector) in _jobPriorities)
        {
            var priority = SelectedJobPriorities.GetValueOrDefault(jobId, JobPriority.Never);
            if (priority != (JobPriority) selector.Selected)
            {
                return true;
            }
        }

        return false;
    }
}
