using Content.Shared._NF.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NF.LateJoin.ListItems;

[GenerateTypedNameReferences]
public sealed partial class CrewListItem : PanelContainer
{
    public sealed class ViewState(
        NetEntity stationEntity,
        string stationName,
        string stationSubtext,
        string stationDescription,
        bool selected,
        string? iconPath,
        ProtoId<VesselPrototype>? vessel)
    {
        public string StationName { get; } = stationName;
        public string StationSubtext { get; } = stationSubtext;
        public string StationDescription { get; } = stationDescription;
        public NetEntity StationEntity { get; } = stationEntity;

        public bool Selected { get; set; } = selected;

        public string IconPath { get; } = iconPath ?? "";
        public ProtoId<VesselPrototype>? Vessel { get; } = vessel;
    }

    public CrewListItem(ViewState state)
    {
        RobustXamlLoader.Load(this);

        StationName.Text = state.StationName;
        StationSubtext.Text = state.StationSubtext;

        // Disallow repeated selection of same station that does UI reloads.
        StationButton.Disabled = state.Selected;

        if (state.IconPath.Length > 0)
        {
            StationIcon.TexturePath = state.IconPath;
        }
    }
}
