using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.LateJoin.ListItems;

[GenerateTypedNameReferences]
public sealed partial class JobListItem : Button
{
    public sealed class ViewState(string jobId, string jobName, string toolTip, bool disabled, Texture? jobIcon)
    {
        public string JobId { get; } = jobId;
        public string JobName { get; } = jobName;

        public bool Disabled { get; } = disabled;

        public string ToolTip { get; } = toolTip;

        public Texture? JobIcon { get; } = jobIcon;
    }

    public JobListItem(ViewState state)
    {
        RobustXamlLoader.Load(this);
        JobText.Text = state.JobName;
        JobIcon.Texture = state.JobIcon;
        ToolTip = state.ToolTip;
        Disabled = state.Disabled;
    }
}
