using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.LateJoin.ListItems;

[GenerateTypedNameReferences]
public sealed partial class StationPickerListItem : PanelContainer
{

    public StationPickerListItem(Controls.StationPickerControl.StationItemViewState state)
    {
        RobustXamlLoader.Load(this);

        StationName.Text = state.StationName;
        StationSubtext.Text = state.StationSubtext;

        // Disallow repeated selection of same station that does UI reloads.
        StationButton.Disabled = state.Selected;

        if (state.IconPath.Length > 0)
        {
            StationIcon.TexturePath = state.IconPath;
        }
    }
}
