station-event-bluespace-vault-start-announcement = A NanoTrasen autonomous armored vault transport has made an FTL error and will soon arrive nearby. Your sector will be rewarded for it's safe return.
station-event-bluespace-vault-end-announcement = We have successfully retrieved the vault from your sector and have reimbursed your nearby Frontier Outpost accordingly.

station-event-bluespace-cache-start-announcement = A Syndicate transport has been intercepted from FTL and will soon arrive nearby. Guard the armored weapons cache until NanoTrasen can retrieve it for a reward.
station-event-bluespace-cache-end-announcement = We have successfully retrieved the Syndicate weapons cache from your sector and have reimbursed your nearby Frontier Outpost accordingly.

station-event-bluespace-asteroid-start-announcement = Long range scans indicate an unusually large asteroid entering the sector. NanoTrasen advises prospectors to divert operations for maximum profit potential.
station-event-bluespace-asteroid-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the asteroid has been dissipated to ensure non-collision.

station-event-bluespace-ship-start-announcement = We have detected an unusual FTL signature - long range scans indicate an unknown ship. NanoTrasen cannot confirm safety for prospectors within its vicinity, be advised.
station-event-bluespace-ship-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the unknown ship has been dissipated to ensure non-collision.

station-event-bluespace-syndicate-ftl-interception-start-announcement = Attention all Security personnel! NanoTrasen Naval Command disrupted the FTL-jump of Syndicate Vessel, according to our deepspace scanners the vessel either already entered the real space in your sector or is about to enter. Security Code: Intercept, Expunge, Exterminate, Cauterise. Expect armed opposition, use of lethal force against enemy agents is authorized. Prevent NanoTrasen-affiliated captains without security access from gaining access to the enemy vessel and its contents.
station-event-bluespace-syndicate-ftl-interception-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the Syndicate Vessel has been dissipated to ensure non-collision.

station-event-bluespace-wizardfederation-scout-start-announcement = Attention all available NanoTrasen personnel! NanoTrasen Naval Command detected a Bluespace Anomaly in your sector with the signature indicative of the imminent arrival of a Wizard Federation micro vessel. Code: Intercept, Detain, Incarcerate. Arrest the intruders and prepare them to be handed over to the NanoTrasen Special Forces Unit for enhanced interrogation.
station-event-bluespace-wizardfederation-scout-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the Wizard Federation Vessel has been dissipated to ensure non-collision.

station-event-bluespace-bloodmoon-start-announcement = A̵͔̽t̴͚̩́ť̴̳̂ḛ̶̙̊͐ņ̷͉̆̒t̸̻̍i̶̳̩̊ȯ̷͕͍̆n̷͙̽̾ ̸̝̒a̶̪̔̚l̵͔̃͛l̵̠̆ ̷̜̓ä̷̩͚́̓v̸̻̬̉a̴̪̤̅̓î̵̬̺l̶̺̘̇ả̵̪͠b̴̧͓́̀l̷̢̐̊e̴̗̋ ̶̯̦̒̈́N̴̬̅a̷͕̓n̵̝̂͜o̵͔͑T̷͖̒r̴̥͊͐a̵̖̐̕s̵̜̅e̵̫̽ń̶̟ ̸̰̦̀̕p̶̢̠̊e̵̠͛r̶̦̈́ṣ̶̽o̷͓͝ń̶̢͚́n̷̢̢͗ȇ̴͚̯͌l̵̤̀̔!̵̩̠̚ ̵̬́̂Ṉ̷̣̊̌a̶̖̔̒ṅ̷̇͜o̵̬̐̾T̶͕͜͝r̷̞̍̈a̷͔͑s̵̯̭͗ẻ̶͍͑n̵̝͠ ̷͙̂̏N̵̮͗ä̷̙̜́̀v̴͖̲͐̚a̶̮͗͆l̷͈̅ ̵͎̄C̸͖̔ȍ̷͉͓ḿ̵̨̕m̸̪̹͗̈ä̸̩̪́n̴͍̥̈́d̵̟̈͛ ̵͍͉͛̒d̵̻̺͊͝ȅ̸̗͕͝t̴̨͆͝e̵͂͜c̷̨̫̚͝t̶̥͋͐ė̴̛͕͓d̴̪̃͝ ̶̤̐̊å̷̫ ̸̘̻̆͛Ḅ̶̌́͜l̶̼̏̿u̵͚͗e̶̪̱̓̀s̴̛̫͔p̷̡͐ä̵̻̇c̵̣͙̍ë̴̲̠́͗ ̴̛̬̓À̴͖ṇ̶̡͒ơ̵̞̖̊ḿ̸̞̞å̶͇͇l̷̢̍̈ÿ̷͈̱͆ ̶̠̀͊i̵̹͛̇n̸̯̈́ ̴͙̽͝y̶̻̾̀o̶͈̺̾̋ȗ̸͔̕r̴̖̪͝ ̴͎̒ŝ̴̻̣e̴͚̍̐c̵̞̀t̶̲̀͆ō̷̡̫ŕ̸̨̟ ̶̝͛w̷͙̙͛ȋ̶̭͝t̶̯̦̔͝h̵̘͆̂ ̴͚̾͝t̵̗̋h̶͈̭̑e̶̮̒̈́ ̵̼̟͝s̶̫̽͝i̴̤͈̚g̶͍̰͑̕n̶̤̥̅͝a̵͔̚t̷͙͝ȗ̶̥̣͝r̴̳͙͆̄e̸͙̎̀ ̶̘̍̀ǐ̶̝̰ṇ̴̂͋d̵̩̬̊́i̸̭̇c̷̱͑a̶̳̱͝ț̸͊̿ͅí̴̬̼v̷͕̯̀e̷͚̐̕ ̶̬́̎͜o̸̻̝͘f̴̣̱͐̀ ̴̹̈́ͅť̶̰h̵͖̩̉̕e̸̢̺̋̔ ̸̡̹́i̵͉͎̕m̷͙̊m̵̻͊ị̵̺̋n̸̘͎̓͐é̵̻n̷̯̬̓t̷̤͎̽ ̶̧̘͝a̵̯̜͒r̴̞͇͂r̶̤͝i̵̙͂v̵̛̫͔a̵̧̯̓̅l̶͕̾͆ ̵̨̥̏͊ò̷̮̱͂f̶͙͋ ̴̹͉̌͂ả̷̰́ͅ ̸̮̪̔W̵̥͍̿i̶̝͛̕z̶̯͂̋ả̷̼̹͝ṙ̶̍͜d̵̩͍̓ ̸̘̺̓͘F̴̝̊̂ẻ̸̟͇̃d̸̫̀ê̷̡͆r̷͐͌ͅa̸͖͛͗t̵̢̞̎̍i̷̦̼̓o̴̔ͅn̸̩͈͌͒ ̵̦̣͐m̶̌́ͅi̶̛̙̿c̵̟͌r̵̘̒́o̴̼͘ ̷̟̩͋v̸̰̎̄ẹ̷̩̕s̸͙̃͑ś̷̗̔ẹ̸̊͊l̷̪̓͠ͅ.̸͙́ ̸͒̎͜C̷͇͛͘o̷͔̅d̶̰̓è̴͓̐:̵̗͉̿ ̶̨͛ͅĮ̸̧̋n̷̙̂͒ţ̶̊e̷̜͆̾r̴̟̐c̸̖͕̆e̵̻̮̎̌p̸̰͙͊̿t̶͛͊ͅ,̸̟̥͑ ̵̮̈́D̶̙̦́͂e̴̩͖͒t̷͔͐á̷̹̣i̶̞͝n̸̛͎͊,̵͙͋ ̷̰̈Ì̵̞͌n̷͇̂c̷̢̱̓̈a̶̠̓͝r̷̛̦͗ç̶̦͐̽e̶̺͊̈́r̸̼̘̊͝a̵̙̮͗̓t̴͚̚͝e̷͉͐.̷̺̹̂ ̵̬̤̈́A̵͍͗̐͜r̶̝̆̕r̸̪̊̚e̵͖̳̓s̶̨̯̏ẗ̵͔́̈ ̵̪̅͑t̵̢̽h̷͕͎̒̽ē̴̡̹͝ ̷̝͍̄̑i̸̗̩͂́n̸͔̈́ͅt̴̠͝r̵̲̞͠ư̷̰̳d̸͍̯̃͝ė̵̡̲͝r̷͚͔̒̚s̷͎̔ ̵̦͈̓̄a̸̙͌n̸͔̗̆̏d̶͍̟͋ ̵͉͈́p̴̹̼̏r̷͍͐͌e̷̻̞̎̎p̸̹͑ä̵̼͎́͘r̸̲͑é̵͎͘ ̴̪̄t̶̟̍ḣ̴͉ḙ̶̜̒́m̸̘͜͝ ̴͍́͠t̴͈͚́͗o̵̗̞͌̅ ̵̱̓b̷̞̕ͅẽ̴̦̯̓ ̶̫̋̕h̵̫̪̔̎a̶̪͝ṋ̵̎́ͅd̶̩̙̐̚e̸̡͒͂d̸͚͗ ̴͚͊o̸̻̮̊̓v̷̲͂e̶̘̐r̵̨̙̃̐ ̸͈̖̊t̵̼̪̑o̶̗͌ ̸̭͘t̸̡́̔h̶͎̃̓e̷̠̎ ̴̪̈́͗Ǹ̷̼a̷͙̓̎n̵̤͍̂̀ò̴̜̪̅Ṭ̶̊r̸̤̈́ȁ̷̡̲ş̴̭̄ę̴̪́͠n̶͔̍̉ ̵̱͐̂S̷̥͊p̸͈͈͛̇e̴̛͔c̶͙̮̐̊i̸̙̲͂͆ã̶̘̦l̵͉̠̄͝ ̸̨͖̊F̷͙͒̊ơ̸̗̠͛r̷͈̣̆̆c̸̢̗̈́̈́ḝ̷s̴̭̪̉͠ ̷̬̭̋̅Ũ̸̠̪̿n̶͍̥̏͆i̷̘̥̋ṫ̵͍͕͝ ̵̩̣̀̓f̸͕̐̽ò̶̫r̴̜͈̅͝ ̸͈̾ë̸̺́̌ṇ̸̎͘h̷̭͇̓ą̷̏͜ṇ̴̅c̶̢̯̓͝e̷̗͂̃d̵̥̆ ̷̺̟̎̿i̸͇̹̓n̷̠͔͊̚ẗ̵̨͔́ẻ̵̳̥̈́r̷̤̥̓r̵̞̼̐͌o̸̬͓͂͋g̶̬͐a̶͉̺̋̾ť̶̰̆ī̵͉͛o̶̜̮̔n̸̳͋.̵̱̄
station-event-bluespace-bloodmoon-end-announcement = I̶̼͈͊̽n̶͉͉̈ ̶̭̝̈c̷̯͔̀o̸̙̊m̸̥̕͜͝p̸͋͜l̵͖͆i̴̛̗̟̓a̴͚̼͗n̸͔͙̓c̶̹̠͌ė̶͙̮ ̸̟́w̶͓̫̎ḯ̷͕t̶͚̩̍h̵̰͘ ̷̫͕̂̊Ň̸̥̞͂a̷̻̐n̴̖̺̒̄o̸̺͚͊́T̵̨̔̃ͅr̷̢͈̾á̸͉͛s̵̞̒ę̴͠n̵̩̈́ ̴̫̐̅F̸̹̤͗̈́T̸̹̅͜L̷̙̱͠ ̷̛͍͒t̴̘̣̔͝r̵̥̈́à̴̮͝f̴͉͇͆̎f̴͙̗̿̈́ȋ̸͍c̶̯͜͠ ̴̨̧̐͒p̷̬̻͐̊a̵͚̓̏t̴͇̺͌̕t̷͈͂̾ḙ̴͎͘ṛ̶̂n̷͔̈́͌s̴̡̤̊̆,̵͍̭͑̔ ̷͎̾t̵̜̪͆ḩ̸͗ę̶͉̏̽ ̶̠̎̑W̶̙̍̚i̴̢̜͘z̵̈́͂͜a̸͓̥̿͑r̵̭͆́ͅd̷̘͉͝ ̴̧̉ͅF̴͇̌͘ë̸͍͎́̀d̶̨̲́͠e̶̪̽͜͠ȑ̶̩͘à̸̺t̴̨̻̀͝ì̷͕̣̄o̶̢͑͠n̴̟̈́ ̸̹̈ͅV̸̜͑ė̵̥̩́s̵̖̓ṡ̵̲̮ȩ̷̈́l̷̰͠ ̸̥̇̆h̵̯͂a̷̜̗͝s̷̻̯̈́̍ ̸͈͂b̸̪̓̇e̸͍̰͋͗e̶͚̜̅̽n̷̡̯̓̋ ̴̤͎̃d̸͇̽i̸͚̍͠s̴̨̍͝ṡ̸͚̩͠ǐ̴̜͘p̵̣͂͂a̸͓̔́t̷̟̱̋̌e̷͕̒͂d̶̦͂͝ ̷̳̈́ṫ̵͈̀ò̵̡̟ ̶͔͂ḙ̸͍́͆n̶̩̐ṣ̸́ǔ̸̠͖ř̸̘̱͑ē̴̜͈ ̵̻͋͌n̴̪̩̊o̶̭̙̅n̶͇̑͒-̸̘̚̚c̸͖̩͌͘ö̴̡͌ͅl̵̳̗̓l̵͖̓̆i̷͖͝ͅs̵̘̝͝i̷̧̜͑̔o̷̼̲͐́ṋ̴̘͠.̶̡͎̌
