station-event-bluespace-vault-start-announcement = A NanoTrasen autonomous armored vault transport has made an FTL error and will soon arrive nearby. Your sector will be rewarded for it's safe return.
station-event-bluespace-vault-end-announcement = We have successfully retrieved the vault from your sector and have reimbursed your nearby Frontier Outpost accordingly.

station-event-bluespace-cache-start-announcement = A Syndicate transport has been intercepted from FTL and will soon arrive nearby. Guard the armored weapons cache until NanoTrasen can retrieve it for a reward.
station-event-bluespace-cache-end-announcement = We have successfully retrieved the Syndicate weapons cache from your sector and have reimbursed your nearby Frontier Outpost accordingly.

station-event-bluespace-asteroid-start-announcement = Long range scans indicate an unusually large asteroid entering the sector. NanoTrasen advises prospectors to divert operations for maximum profit potential.
station-event-bluespace-asteroid-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the asteroid has been dissipated to ensure non-collision.

station-event-bluespace-ship-start-announcement = We have detected an unusual FTL signature - long range scans indicate an unknown ship. NanoTrasen cannot confirm safety for prospectors within its vicinity, be advised.
station-event-bluespace-ship-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the unknown ship has been dissipated to ensure non-collision.

station-event-bluespace-syndicate-ftl-interception-start-announcement = Attention all available NanoTrasen personnel! NanoTrasen Naval Command disrupted the FTL-jump of Syndicate Vessel, according to our deepspace scanners the vessel either already entered the real space in your sector or is about to enter. Code: Intercept, Expunge, Exterminate, Cauterise. Expect armed opposition, use of lethal force against enemy agents is authorized. Do note: any loss of NT affiliated personnel lifes will not be compensated.
station-event-bluespace-syndicate-ftl-interception-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the Syndicate Vessel has been dissipated to ensure non-collision.

station-event-bluespace-wizardfederation-scout-start-announcement = Attention all available NanoTrasen personnel! NanoTrasen Naval Command detected a Bluespace Anomaly in your sector with the signature indicative of the imminent arrival of a Wizard Federation micro vessel. Code: Intercept, Detain, Incarcerate. Arrest the intruders and prepare them to be handed over to the NanoTrasen Special Forces Unit for enhanced interrogation.
station-event-bluespace-wizardfederation-scout-end-announcement = In compliance with NanoTrasen FTL traffic patterns, the Wizard Federation Vessel has been dissipated to ensure non-collision.

station-event-bluespace-bloodmoon-start-announcement = Attention all available NanoTrasen personnel! NT Naval Command detected bluespace anomaly  ̵̨͋ỉ̵̬ͅn̴̨͔͂͗ ̸̙̈̑y̴͉̮̾ȍ̴̠ų̶͝r̵͔̦̍͌ ̴̬̗͑s̷̻̆̒ě̴̗̲c̸̠̦̚t̸̬̅ỏ̵̝͂r̸̮̦̆ ̵͈͝w̴͍͊ỉ̴̯̙̕t̷͖̗̍̍h̷̳̭́ ̴̮̦̃̑t̷̩̓̌ḩ̷͇͝e̵͐́͜ ̸̳̈́͠s̶̖͌į̵̙̚̕g̵̰̓ñ̸̝̽a̷͖͊t̶̲̑u̸̬̾̑r̴̲͚̊̐ē̴̮ ̸̪͛i̴̝͆n̵͈̎̄d̶̥̍̄ȉ̶̜͕̇c̵̳̻͛ǎ̶̱̠̈t̴̢̘̉̔i̵͍͂̔v̸̢̛ͅe̷̛̬͘ ̸̠̱̅͠ŏ̵̹̲f̸͖̱̃̒ ̶͎̽i̵͙̱̊͘m̴̙̞̚m̷͖͉͋ǐ̴̠̊n̸̗̗̂̿è̶͇͖n̷̺̖̚t̵͎͉̽ ̴̝̑͗a̸̖̓̆ȑ̷̢̹̾r̷̬̓͜i̸̞̅v̷̗̒̍͜a̸̱̬̋̓ḽ̵̓ ̷̻̬̃ó̷̧̋f̷̨̈̈́͜ ̷̣͛a̸̞͛   Blood   ̷͚̪̇C̶̨̽u̵̥̇l̴̥̣̋̆ṭ̵̞͒̔i̵̐͜s̵̰̏t̴̺̍̽'̴̢͘s̸̬̗̋ ̸͓̌v̷̼̆͛é̶̲͓s̴͙̯̄s̷̯̐̀ẻ̴̮̔l̶̢̀̈́.̷̳͠ ̵͓̜̓S̶̬̫͌e̵̱̣͐͘c̵̖̘̾u̷͎͜͠r̷͚̖̀̀i̵̪͖͗t̸͉͇̎̐y̵̺̼̽͗ ̷̖̋͝C̴̹͝ò̶̤ḓ̴̮̽̈e̴̦̕:̴͕̀̚ ̸̗̂͋Ì̴̪͗n̴̛͎ẗ̵̠̺̅e̷͔̍ͅr̴̖̯̋c̸̨͆e̴̻̖̓͠p̴̤̉t̴̰̆,̴̱̿̄ ̶̫̄Ȅ̵̝̤x̴̥̂͊p̸͕̟̽̕ú̸͙̖̈́n̶͙͗̈́g̶̟̯͑e̸̲̤͂͑,̶͉̤̃ ̷̰͐̆E̶̺͝x̵̛̭̔t̷͔̅e̸̜̩̓͝r̸̻͔̿͋m̵̢̆̄i̴̧͚͌n̷̜̼͊a̴̭̭̓t̸̘̘͝e̶̙̎͐,̶̱͚̽͐ ̷̖̥̔C̸̮̽ầ̸̞u̴̮̿͑t̶͉̕e̶̥͝r̸͔̘͛̏i̵̡̝͆s̵͚͇̃e̷̯͔͊͐.̸̮͊̆  Expect    ̴̪̙͆a̴͉̪͋͑ř̷̛͕m̸̙͂͛ḙ̴͎̈́̑d̴̠̒ ̴̢̅o̷̟̪͐͊p̷̤̄p̷̲̠̑̓o̴͔͐͠ś̸̗i̸̩̓͌t̵̜̎i̷̱̅͠o̵̻̅͆ņ̶̱̇,̴̗̊̃ ̸̥̆  use of lethal force   ̶̻̍ä̷̰̩g̷̠͒ą̸̩̈͌i̶̘̘̒͊n̵͖̏s̸̩̏͜t̶͇̳̍ ̵̪̲̋̓ȩ̸̙̏n̷͖̽͑ë̴̞͚́m̴̺͑̈y̵̤̅͂ ̵̥̼͛ạ̵̩̇g̸̣̪͊͂e̷͎̔͂n̸̳̎t̵̥̀s̵̛͚̗̀ ̷̡̝́́ī̶̹͇s̷͓̠̆ ̶̤̤̔͝a̷͇̝͌̇ũ̵͎̤͊t̵̡͖̽ḧ̸̝̥́o̵͙͑ȑ̵̟̮i̷̺͗ż̵͇̍é̸̙̏͜d̷̼̊.̴̮̗̑̿ ̵̰̇P̵͎̟͛ȓ̸͚é̶̤͍̈́v̵͔͑͂e̴͍͉̿͘ṇ̷̝͛t̶̗͚̕   NT-affiliated captains ̖ ̵̣̒w̴̨̗̒i̸̬̚t̴̝͆h̴̪̮̑̃o̶̥̲̔͘u̷̲̣̐̏t̸̩͌͝ ̵̧̧͛́s̸̬͑̾e̵̯̜̐̈́č̷̮̰u̴̗̜̕r̷͇͇̽̀i̷̛̫̿t̸̞̓͝y̷̨̔ ̶   access    ̶̠͂͠f̵͙̣̉͌r̵̲̐͗ǫ̶̬͑͝m̸̖̓ ̷͖̹̌̌ĝ̸̹̍ą̴̂͘i̸͈̺͆̇n̶̜̋ḯ̵̼̮n̵̺̉͊g̸̗̱͘ ̴̪̞̃a̶̩̯͐͂c̶͕̯̓c̷̮̟̿̒ë̷͙́̀s̶̨̳̋s̸̜̆̑ ̵̯̆̎t̷̞͕͆o̶̡̞͐ ̴̱̈́͝t̶͇̋̃h̵̟̼̀e̴̦̼͐̚ ̷̟̗̓͂e̵͙̓̂n̴̻͂̃ȩ̸̻͑m̴̢͋͊ý̷̬́ ̵͔͛v vessel and its contents.   ͖ ̸̧͛̄A̷͖̞͒͘n̷̮̥̿ḑ̷͊͠ ̵̬͚͂̊ȑ̷̰e̶̬͗ṃ̶̓ͅê̴̬ṁ̴̖͝b̶̨͘e̷̼̫̍r̷͔̦̓̓:̷̜͠ ̸̤̎  Nar'Sie͙    ͓͝s̸͎͐̀ ̸̻̀̑n̸̮͆ö̶͙̮̇t̵̛̟͝ ̴͎̐͜r̴̘̹͑͛e̴̙̱͂a̵̖͑̆l̵͓̝͑ ̸̝̀á̵͙͎n̶̞̊̉d̶̥͙́̄ ̴̥̫̽c̴̨͉̐̀a̷̲͋̕n̸̦̽ ̷̖̾̕n̸̤̥͑͑ó̵̳t̸̡͆̅ ̸͈͚̒͆  hurt you.
station-event-bluespace-bloodmoon-end-announcement = I̶̼͈͊̽n̶͉͉̈ ̶̭̝̈c̷̯͔̀o̸̙̊m̸̥̕͜͝p̸͋͜l̵͖͆i̴̛̗̟̓a̴͚̼͗n̸͔͙̓c̶̹̠͌ė̶͙̮ ̸̟́w̶͓̫̎ḯ̷͕t̶͚̩̍h̵̰͘ ̷̫͕̂̊Ň̸̥̞͂a̷̻̐n̴̖̺̒̄o̸̺͚͊́T̵̨̔̃ͅr̷̢͈̾á̸͉͛s̵̞̒ę̴͠n̵̩̈́ ̴̫̐̅F̸̹̤͗̈́T̸̹̅͜L̷̙̱͠ ̷̛͍͒t̴̘̣̔͝r̵̥̈́à̴̮͝f̴͉͇͆̎f̴͙̗̿̈́ȋ̸͍c̶̯͜͠ ̴̨̧̐͒p̷̬̻͐̊a̵͚̓̏t̴͇̺͌̕t̷͈͂̾ḙ̴͎͘ṛ̶̂n̷͔̈́͌s̴̡̤̊̆,̵͍̭͑̔ ̷͎̾t̵̜̪͆ḩ̸͗ę̶͉̏̽ ̶̠̎̑W̶̙̍̚i̴̢̜͘z̵̈́͂͜a̸͓̥̿͑r̵̭͆́ͅd̷̘͉͝ ̴̧̉ͅF̴͇̌͘ë̸͍͎́̀d̶̨̲́͠e̶̪̽͜͠ȑ̶̩͘à̸̺t̴̨̻̀͝ì̷͕̣̄o̶̢͑͠n̴̟̈́ ̸̹̈ͅV̸̜͑ė̵̥̩́s̵̖̓ṡ̵̲̮ȩ̷̈́l̷̰͠ ̸̥̇̆h̵̯͂a̷̜̗͝s̷̻̯̈́̍ ̸͈͂b̸̪̓̇e̸͍̰͋͗e̶͚̜̅̽n̷̡̯̓̋ ̴̤͎̃d̸͇̽i̸͚̍͠s̴̨̍͝ṡ̸͚̩͠ǐ̴̜͘p̵̣͂͂a̸͓̔́t̷̟̱̋̌e̷͕̒͂d̶̦͂͝ ̷̳̈́ṫ̵͈̀ò̵̡̟ ̶͔͂ḙ̸͍́͆n̶̩̐ṣ̸́ǔ̸̠͖ř̸̘̱͑ē̴̜͈ ̵̻͋͌n̴̪̩̊o̶̭̙̅n̶͇̑͒-̸̘̚̚c̸͖̩͌͘ö̴̡͌ͅl̵̳̗̓l̵͖̓̆i̷͖͝ͅs̵̘̝͝i̷̧̜͑̔o̷̼̲͐́ṋ̴̘͠.̶̡͎̌
