using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LedgerEntry : BoxContainer
{
    public LedgerEntry()
    {
        RobustXamlLoader.Load(this);
    }
}
