using Content.Shared.DeviceLinking;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Localization;

namespace Content.Client._NF.DeviceLinking.UI;

[GenerateTypedNameReferences]
public sealed partial class RngDeviceWindow : DefaultWindow
{
    public event Action<bool>? OnMuteToggled;

    public RngDeviceWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("rng-device-title");

        MuteCheckBox.OnToggled += OnCheckBoxToggled;
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        OnMuteToggled?.Invoke(args.Pressed);
    }

    public void UpdateState(RngDeviceBoundUserInterfaceState state)
    {
        MuteCheckBox.Pressed = state.IsMuted;
    }
}
