// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <143940725+FaDeOkno@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <logkedr18@gmail.com>
// SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client._Goobstation.Research.UI;
using Content.Client.Lathe;
using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Shared._Goobstation.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Log;
using Robust.Shared.Prototypes;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyTechnologyInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype>? BuyAction;

    public FancyTechnologyInfoPanel(TechnologyPrototype proto, bool hasAccess, ResearchAvailability availability, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("research");

        var lathe = _ent.System<LatheSystem>();
        var research = _ent.System<ResearchSystem>();
        Prototype = proto;

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(_proto.Index(proto.Discipline).Icon);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon); // Frontier

        InitializePrerequisites(proto, research, sprite);

        InitializeRecipeUnlocks(proto, lathe, sprite);

        ResearchButton.ToolTip = !hasAccess
            ? Loc.GetString("research-console-no-access-popup")
            : null;

        ResearchButton.Text = availability == ResearchAvailability.Researched
            ? Loc.GetString("research-console-menu-server-researched-button")
            : ResearchButton.Text;

        Color? color = availability switch
        {
            ResearchAvailability.Researched => Color.LimeGreen,
            ResearchAvailability.PrereqsMet => Color.Crimson,
            ResearchAvailability.Unavailable => Color.Crimson,
            _ => null
        };
        TechnologyCostLabel.SetMessage(
            Loc.GetString("research-console-tech-cost-label", ("cost", proto.Cost)),
            defaultColor: color
        );

        ResearchButton.Disabled = !hasAccess || availability != ResearchAvailability.Available;

        // Replace the event handling method to use a simpler approach
        ResearchButton.OnPressed += args =>
        {
            _sawmill.Debug($"Research button pressed for {proto.ID}");
            if (BuyAction != null)
            {
                _sawmill.Debug($"Triggering BuyAction for {proto.ID}");
                BuyAction.Invoke(proto);
            }
            else
            {
                _sawmill.Error($"BuyAction is null for {proto.ID}");
            }
        };

        _sawmill.Debug($"Created tech panel: {proto.ID}, availability: {availability}, button disabled: {ResearchButton.Disabled}");
    }

    private void InitializePrerequisites(TechnologyPrototype proto, ResearchSystem research, SpriteSystem sprite)
    {
        // Frontier: required techs always visible, label in required techs
        foreach (var child in RequiredTechContainer.Children.ToList())
        {
            if (child != NoPrereqLabel)
                RequiredTechContainer.RemoveChild(child);
        }
        // End Frontier: required techs always visible, label in required techs
        NoPrereqLabel.Visible = proto.TechnologyPrerequisites.Count == 0;
        foreach (var techId in proto.TechnologyPrerequisites)
        {
            var tech = _proto.Index(techId);
            var description = research.GetTechnologyDescription(tech, true, false, true);
            RequiredTechContainer.AddChild(new MiniTechnologyCardControl(tech, _proto, sprite, description));
        }
    }

    private void InitializeRecipeUnlocks(TechnologyPrototype proto, LatheSystem lathe, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var recipeId in proto.RecipeUnlocks)
        {
            var recipe = _proto.Index(recipeId);
            UnlocksContainer.AddChild(new MiniRecipeCardControl(proto, recipe, _proto, sprite, lathe));
        }
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        // No need to explicitly remove handlers as the control is being destroyed
    }
}
