using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.SafetyDepositBox.BUI;
using Content.Shared._WF.SafetyDepositBox.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WF.SafetyDepositBox;

[GenerateTypedNameReferences]
public sealed partial class SafetyDepositConsoleWindow : FancyWindow
{
    public event Action<SafetyDepositBoxSize>? OnPurchasePressed;
    public event Action? OnDepositPressed;
    public event Action<Guid>? OnWithdrawPressed;
    public event Action<Guid>? OnReclaimPressed;

    public SafetyDepositConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        PurchaseTrialButton.OnPressed += _ => OnPurchasePressed?.Invoke(SafetyDepositBoxSize.Trial);
        PurchaseSmallButton.OnPressed += _ => OnPurchasePressed?.Invoke(SafetyDepositBoxSize.Small);
        PurchaseMediumButton.OnPressed += _ => OnPurchasePressed?.Invoke(SafetyDepositBoxSize.Medium);
        PurchaseLargeButton.OnPressed += _ => OnPurchasePressed?.Invoke(SafetyDepositBoxSize.Large);
        DepositButton.OnPressed += _ => OnDepositPressed?.Invoke();
    }

    public void UpdateState(SafetyDepositConsoleState state)
    {
        // Update purchase buttons with costs
        PurchaseTrialButton.Disabled = false; // Bank account check happens server-side
        PurchaseTrialButton.Text = Loc.GetString("safety-deposit-console-purchase-trial", ("cost", state.TrialBoxCost.ToString("N0")));

        PurchaseSmallButton.Disabled = false; // Bank account check happens server-side
        PurchaseSmallButton.Text = Loc.GetString("safety-deposit-console-purchase-small", ("cost", state.SmallBoxCost.ToString("N0")));

        PurchaseMediumButton.Disabled = false;
        PurchaseMediumButton.Text = Loc.GetString("safety-deposit-console-purchase-medium", ("cost", state.MediumBoxCost.ToString("N0")));

        PurchaseLargeButton.Disabled = false;
        PurchaseLargeButton.Text = Loc.GetString("safety-deposit-console-purchase-large", ("cost", state.LargeBoxCost.ToString("N0")));

        // Update deposit button
        DepositButton.Disabled = !state.HasBoxInSlot || state.BoxInSlot == null;

        // Update box slot status
        if (state.HasBoxInSlot && state.BoxInSlot != null)
        {
            BoxSlotLabel.Text = Loc.GetString("safety-deposit-console-box-in-slot",
                ("id", state.BoxInSlot.BoxId.ToString()[..8]));
        }
        else
        {
            BoxSlotLabel.Text = Loc.GetString("safety-deposit-console-no-box-in-slot");
        }

        // Update owned boxes list
        OwnedBoxesContainer.RemoveAllChildren();

        if (state.OwnedBoxes.Count == 0)
        {
            var noBoxesLabel = new Label
            {
                Text = Loc.GetString("safety-deposit-console-no-boxes"),
                StyleClasses = { "LabelSecondaryColor" },
                HorizontalAlignment = Control.HAlignment.Center,
                Margin = new Thickness(0, 20)
            };
            OwnedBoxesContainer.AddChild(noBoxesLabel);
        }
        else
        {
            // Sort boxes newest first (by BoxId descending)
            var sortedBoxes = state.OwnedBoxes.OrderByDescending(b => b.BoxId).ToList();

            var index = 0;
            foreach (var box in sortedBoxes)
            {
                // Create a clean row similar to shipyard
                var rowPanel = new PanelContainer
                {
                    HorizontalExpand = true,
                    StyleClasses = { "AngleRect" },
                    // Alternate row colors for better readability
                    ModulateSelfOverride = index % 2 == 0 ? new Color(0.15f, 0.15f, 0.15f) : new Color(0.12f, 0.12f, 0.12f)
                };

                var rowContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(8, 4)
                };

                // Box info label - shows nickname if available, otherwise box ID and size
                var boxInfoText = !string.IsNullOrEmpty(box.Nickname)
                    ? $"{box.Nickname} ({box.BoxSize})"
                    : $"Box {box.BoxId.ToString()[..8]}... ({box.BoxSize})";

                var boxIdLabel = new Label
                {
                    Text = boxInfoText,
                    HorizontalExpand = true,
                    VerticalAlignment = Control.VAlignment.Center
                };

                // Status Label - fixed width, right aligned
                string statusText;
                Color statusColor;

                if (box.IsDeposited)
                {
                    statusText = Loc.GetString("safety-deposit-console-box-deposited");
                    statusColor = Color.LightGreen;
                }
                else if (box.LastWithdrawnRoundId.HasValue && box.LastWithdrawnRoundId.Value != state.CurrentRoundId)
                {
                    // Box was withdrawn in a previous round - it's lost
                    statusText = Loc.GetString("safety-deposit-console-box-lost");
                    statusColor = Color.Red;
                }
                else
                {
                    // Box was withdrawn in current round - it's in world
                    statusText = Loc.GetString("safety-deposit-console-box-in-world");
                    statusColor = Color.Yellow;
                }

                var statusLabel = new Label
                {
                    Text = statusText,
                    MinWidth = 80,
                    Align = Label.AlignMode.Right,
                    Margin = new Thickness(0, 0, 5, 0),
                    HorizontalAlignment = Control.HAlignment.Right,
                    VerticalAlignment = Control.VAlignment.Center,
                    FontColorOverride = statusColor
                };

                // Determine if box is lost (withdrawn in previous round with no items)
                var isLost = box.LastWithdrawnRoundId.HasValue &&
                             box.LastWithdrawnRoundId.Value != state.CurrentRoundId &&
                             !box.IsDeposited;

                // Action button - either Withdraw or Reclaim depending on state
                var actionButton = new Button
                {
                    Text = isLost
                        ? Loc.GetString("safety-deposit-console-reclaim-button")
                        : Loc.GetString("safety-deposit-console-withdraw-button"),
                    Disabled = !box.IsDeposited && !isLost,
                    MinWidth = 100,
                    HorizontalAlignment = Control.HAlignment.Right,
                    VerticalAlignment = Control.VAlignment.Center
                };

                var boxId = box.BoxId;
                if (isLost)
                {
                    actionButton.OnPressed += _ => OnReclaimPressed?.Invoke(boxId);
                }
                else
                {
                    actionButton.OnPressed += _ => OnWithdrawPressed?.Invoke(boxId);
                }

                rowContainer.AddChild(boxIdLabel);
                rowContainer.AddChild(statusLabel);
                rowContainer.AddChild(actionButton);
                rowPanel.AddChild(rowContainer);
                OwnedBoxesContainer.AddChild(rowPanel);

                index++;
            }
        }
    }
}
